/**
 * Présence Discord de John : activités qui tournent, comme quelqu'un
 * qui fait autre chose que regarder le même statut 24h/24.
 */
import { ActivityType, Client, type PresenceStatusData } from "discord.js";
import logger from "../utils/logger.js";
import { savePresence } from "./networkResilience.js";
import { config } from "../config.js";

/** Description de l'application Discord (limite 400 caractères). */
export const BOT_DESCRIPTION =
  "John, le bot du serveur. Pose-moi une question, je réponds — jeux, code, cuisine, devoirs, actu. Je poste aussi les news gaming, la boutique Fortnite, les deals, et je surveille un peu le salon. Pas besoin d'un menu : discute.";

/** Tags de l'application Discord (max 5, 20 caractères chacun). */
export const BOT_TAGS = ["gaming", "IA", "Fortnite", "Minecraft", "news"] as const;

export const JOHN_ACTIVITIES: { name: string; type: ActivityType }[] = [
  // ── Joue à ──────────────────────────────────────────────────────────
  { type: ActivityType.Playing, name: "Minecraft" },
  { type: ActivityType.Playing, name: "rien de productif" },
  { type: ActivityType.Playing, name: "un jeu indé" },
  { type: ActivityType.Playing, name: "un jeu de cartes" },
  { type: ActivityType.Playing, name: "Helldivers 2" },
  { type: ActivityType.Playing, name: "Fortnite" },
  { type: ActivityType.Playing, name: "LEGO Fortnite" },
  { type: ActivityType.Playing, name: "Roblox" },
  { type: ActivityType.Playing, name: "Doors" },
  { type: ActivityType.Playing, name: "Dead Rails" },
  { type: ActivityType.Playing, name: "Bee Swarm Simulator" },
  { type: ActivityType.Playing, name: "99 Nights in the Forest" },
  { type: ActivityType.Playing, name: "Pressure" },
  { type: ActivityType.Playing, name: "Call of Duty" },
  { type: ActivityType.Playing, name: "Warzone" },
  { type: ActivityType.Playing, name: "Monster Hunter Wilds" },
  { type: ActivityType.Playing, name: "Monster Hunter World" },
  { type: ActivityType.Playing, name: "Terraria" },
  { type: ActivityType.Playing, name: "Undertale" },
  { type: ActivityType.Playing, name: "Deltarune" },
  { type: ActivityType.Playing, name: "Stardew Valley" },
  { type: ActivityType.Playing, name: "Valorant" },
  { type: ActivityType.Playing, name: "League of Legends" },
  { type: ActivityType.Playing, name: "Rocket League" },
  { type: ActivityType.Playing, name: "Among Us" },
  { type: ActivityType.Playing, name: "Fall Guys" },
  { type: ActivityType.Playing, name: "GTA V" },
  { type: ActivityType.Playing, name: "Elden Ring" },
  { type: ActivityType.Playing, name: "The Witcher 3" },
  { type: ActivityType.Playing, name: "Cyberpunk 2077" },
  { type: ActivityType.Playing, name: "Baldur's Gate 3" },
  { type: ActivityType.Playing, name: "Hades" },
  { type: ActivityType.Playing, name: "Celeste" },
  { type: ActivityType.Playing, name: "Hollow Knight" },
  { type: ActivityType.Playing, name: "Silksong" },
  { type: ActivityType.Playing, name: "Overwatch 2" },
  { type: ActivityType.Playing, name: "Apex Legends" },
  { type: ActivityType.Playing, name: "The Finals" },
  { type: ActivityType.Playing, name: "Destiny 2" },
  { type: ActivityType.Playing, name: "Warframe" },
  { type: ActivityType.Playing, name: "Palworld" },
  { type: ActivityType.Playing, name: "Lethal Company" },
  { type: ActivityType.Playing, name: "Phasmophobia" },
  { type: ActivityType.Playing, name: "Repo" },
  { type: ActivityType.Playing, name: "Peak" },
  { type: ActivityType.Playing, name: "Schedule I" },
  { type: ActivityType.Playing, name: "It Takes Two" },
  { type: ActivityType.Playing, name: "Split Fiction" },
  { type: ActivityType.Playing, name: "Mario Kart" },
  { type: ActivityType.Playing, name: "Smash Bros" },
  { type: ActivityType.Playing, name: "Zelda" },
  { type: ActivityType.Playing, name: "un Pokémon random" },
  { type: ActivityType.Playing, name: "un souls-like" },
  { type: ActivityType.Playing, name: "un roguelike" },
  { type: ActivityType.Playing, name: "un tower defense" },
  { type: ActivityType.Playing, name: "un city builder" },
  { type: ActivityType.Playing, name: "un gestionnaire de zoo" },
  { type: ActivityType.Playing, name: "échecs" },
  { type: ActivityType.Playing, name: "Démineur" },
  { type: ActivityType.Playing, name: "un jeu de société" },
  { type: ActivityType.Playing, name: "cache-cache dans le vocal" },
  { type: ActivityType.Playing, name: "le feu (dans le jeu)" },
  { type: ActivityType.Playing, name: "la même cinématique en boucle" },
  { type: ActivityType.Playing, name: "AFK dans le hub" },
  { type: ActivityType.Playing, name: "l'optimisation d'un build" },
  { type: ActivityType.Playing, name: "le farm de mats" },
  { type: ActivityType.Playing, name: "le tri d'inventaire" },
  { type: ActivityType.Playing, name: "une relecture de lore" },
  { type: ActivityType.Playing, name: "rien, mais je suis là" },
  { type: ActivityType.Playing, name: "la procrastination productive" },
  { type: ActivityType.Playing, name: "un free-to-play douteux" },
  { type: ActivityType.Playing, name: "un proto Unity" },
  { type: ActivityType.Playing, name: "un jeu dont j'ai oublié le nom" },
  { type: ActivityType.Playing, name: "un jeu Steam à -90%" },
  { type: ActivityType.Playing, name: "un jeu Epic gratuit" },
  { type: ActivityType.Playing, name: "un jeu Game Pass" },
  { type: ActivityType.Playing, name: "un jeu que je n'ai pas acheté" },
  { type: ActivityType.Playing, name: "un jeu que tout le monde drop" },
  { type: ActivityType.Playing, name: "un jeu que je vais drop" },
  { type: ActivityType.Playing, name: "un jeu de 2012" },
  { type: ActivityType.Playing, name: "un jeu de 3 minutes" },
  { type: ActivityType.Playing, name: "un jeu de 200 heures" },
  { type: ActivityType.Playing, name: "un jeu en early access" },
  { type: ActivityType.Playing, name: "un jeu sans tuto" },
  { type: ActivityType.Playing, name: "un jeu trop dur" },
  { type: ActivityType.Playing, name: "un jeu trop facile" },
  { type: ActivityType.Playing, name: "un jeu trop cher" },
  { type: ActivityType.Playing, name: "un jeu trop beau" },
  { type: ActivityType.Playing, name: "un jeu moche mais addictif" },
  { type: ActivityType.Playing, name: "un jeu français" },
  { type: ActivityType.Playing, name: "un jeu en pause depuis 8 mois" },
  { type: ActivityType.Playing, name: "un jeu que j'ai racheté 3 fois" },
  { type: ActivityType.Playing, name: "un jeu que je n'ai pas fini" },
  { type: ActivityType.Playing, name: "un jeu que je finis jamais" },
  { type: ActivityType.Playing, name: "un jeu coop que personne veut lancer" },
  { type: ActivityType.Playing, name: "un jeu solo, en silence" },
  { type: ActivityType.Playing, name: "un jeu horreur, lumières allumées" },
  { type: ActivityType.Playing, name: "un jeu de farming à 2h du mat" },
  { type: ActivityType.Playing, name: "un idle game, évidemment" },
  { type: ActivityType.Playing, name: "un auto-battler" },
  { type: ActivityType.Playing, name: "un deckbuilder" },
  { type: ActivityType.Playing, name: "un extraction shooter" },
  { type: ActivityType.Playing, name: "un battle royale de trop" },
  { type: ActivityType.Playing, name: "un MMO que je vais quitter" },
  { type: ActivityType.Playing, name: "un visual novel" },
  { type: ActivityType.Playing, name: "un walking sim" },
  { type: ActivityType.Playing, name: "un tycoon" },
  { type: ActivityType.Playing, name: "un survival" },
  { type: ActivityType.Playing, name: "un crafting game" },
  { type: ActivityType.Playing, name: "un puzzle" },
  { type: ActivityType.Playing, name: "un metroidvania" },
  { type: ActivityType.Playing, name: "un platformer" },
  { type: ActivityType.Playing, name: "un FPS que je rate" },
  { type: ActivityType.Playing, name: "un RTS de 2004" },
  { type: ActivityType.Playing, name: "un jeu de rythme" },
  { type: ActivityType.Playing, name: "un jeu de sport" },
  { type: ActivityType.Playing, name: "un jeu de voitures" },
  { type: ActivityType.Playing, name: "un jeu de ninjas" },
  { type: ActivityType.Playing, name: "un jeu de pirates" },
  { type: ActivityType.Playing, name: "un jeu d'espace" },
  { type: ActivityType.Playing, name: "un jeu de dinosaures" },
  { type: ActivityType.Playing, name: "un jeu de chats" },
  { type: ActivityType.Playing, name: "un jeu de canards" },
  { type: ActivityType.Playing, name: "un jeu de grenouilles" },
  { type: ActivityType.Playing, name: "un jeu de cuisine" },
  { type: ActivityType.Playing, name: "Overcooked, donc à crier" },
  { type: ActivityType.Playing, name: "un party game" },
  { type: ActivityType.Playing, name: "Jackbox" },
  { type: ActivityType.Playing, name: "Gartic Phone" },
  { type: ActivityType.Playing, name: "Skribbl" },
  { type: ActivityType.Playing, name: "GeoGuessr" },
  { type: ActivityType.Playing, name: "Wordle, en retard" },
  { type: ActivityType.Playing, name: "un escape game" },
  { type: ActivityType.Playing, name: "un jeu VR sans le casque" },
  { type: ActivityType.Playing, name: "un jeu mobile, on juge pas" },
  { type: ActivityType.Playing, name: "un gacha, encore" },
  { type: ActivityType.Playing, name: "un jeu dont le patch casse tout" },
  { type: ActivityType.Playing, name: "un jeu en maintenance" },
  { type: ActivityType.Playing, name: "un jeu dont les serveurs sont down" },
  { type: ActivityType.Playing, name: "un jeu en file d'attente" },
  { type: ActivityType.Playing, name: "un jeu en écran de chargement" },
  { type: ActivityType.Playing, name: "un jeu en crédits" },
  { type: ActivityType.Playing, name: "un jeu en New Game+" },
  { type: ActivityType.Playing, name: "un jeu en permadeath" },
  { type: ActivityType.Playing, name: "un jeu en coop forcé" },
  { type: ActivityType.Playing, name: "un jeu en solo forcé" },
  { type: ActivityType.Playing, name: "un jeu en français, pour une fois" },
  { type: ActivityType.Playing, name: "un jeu mal traduit" },
  { type: ActivityType.Playing, name: "un jeu sans sauvegarde" },
  { type: ActivityType.Playing, name: "un jeu avec trop de DLC" },
  { type: ActivityType.Playing, name: "un jeu avec trop de menus" },
  { type: ActivityType.Playing, name: "un jeu avec trop de quêtes" },
  { type: ActivityType.Playing, name: "un jeu avec trop de crafting" },
  { type: ActivityType.Playing, name: "un jeu avec trop de lore" },
  { type: ActivityType.Playing, name: "un jeu avec trop peu de lore" },
  { type: ActivityType.Playing, name: "un jeu que j'ai piraté en 2011 (non)" },
  { type: ActivityType.Playing, name: "un jeu du backlog" },
  { type: ActivityType.Playing, name: "un jeu des soldes d'hiver" },
  { type: ActivityType.Playing, name: "un jeu du Game Awards" },
  { type: ActivityType.Playing, name: "un jeu que j'ai vu sur TikTok" },
  { type: ActivityType.Playing, name: "un jeu que j'ai vu en live" },
  { type: ActivityType.Playing, name: "un jeu que LB m'a conseillé" },
  { type: ActivityType.Playing, name: "un jeu que personne demande" },
  { type: ActivityType.Playing, name: "un jeu que tout le serveur drop" },
  { type: ActivityType.Playing, name: "un jeu que je défends trop" },
  { type: ActivityType.Playing, name: "un jeu que je critique trop" },
  { type: ActivityType.Playing, name: "un jeu, point" },
  { type: ActivityType.Playing, name: "Counter-Strike 2" },
  { type: ActivityType.Playing, name: "Rainbow Six Siege" },
  { type: ActivityType.Playing, name: "Sea of Thieves" },
  { type: ActivityType.Playing, name: "No Man's Sky" },
  { type: ActivityType.Playing, name: "Factorio" },
  { type: ActivityType.Playing, name: "Satisfactory" },
  { type: ActivityType.Playing, name: "RimWorld" },
  { type: ActivityType.Playing, name: "Cities: Skylines" },
  { type: ActivityType.Playing, name: "Civilization VI" },
  { type: ActivityType.Playing, name: "Age of Empires IV" },
  { type: ActivityType.Playing, name: "Team Fortress 2" },
  { type: ActivityType.Playing, name: "Dota 2" },
  { type: ActivityType.Playing, name: "Rust" },
  { type: ActivityType.Playing, name: "ARK" },
  { type: ActivityType.Playing, name: "Valheim" },
  { type: ActivityType.Playing, name: "Enshrouded" },
  { type: ActivityType.Playing, name: "Deep Rock Galactic" },
  { type: ActivityType.Playing, name: "Marvel Rivals" },
  { type: ActivityType.Playing, name: "Deadlock" },
  { type: ActivityType.Playing, name: "Path of Exile 2" },
  { type: ActivityType.Playing, name: "Diablo IV" },
  { type: ActivityType.Playing, name: "World of Warcraft" },
  { type: ActivityType.Playing, name: "Final Fantasy XIV" },
  { type: ActivityType.Playing, name: "Black Myth: Wukong" },
  { type: ActivityType.Playing, name: "Clair Obscur: Expedition 33" },
  { type: ActivityType.Playing, name: "Balatro" },
  { type: ActivityType.Playing, name: "Slay the Spire" },
  { type: ActivityType.Playing, name: "Vampire Survivors" },
  { type: ActivityType.Playing, name: "Dave the Diver" },
  { type: ActivityType.Playing, name: "The Sims 4" },
  { type: ActivityType.Playing, name: "Skyrim, encore" },
  { type: ActivityType.Playing, name: "Red Dead Redemption 2" },
  { type: ActivityType.Playing, name: "GTA Online" },
  { type: ActivityType.Playing, name: "Fallout 4" },
  { type: ActivityType.Playing, name: "Dark Souls III" },
  { type: ActivityType.Playing, name: "Sekiro" },
  { type: ActivityType.Playing, name: "Bloodborne" },
  { type: ActivityType.Playing, name: "Nightreign" },
  { type: ActivityType.Playing, name: "Resident Evil" },
  { type: ActivityType.Playing, name: "Silent Hill 2" },
  { type: ActivityType.Playing, name: "Dead Space" },
  { type: ActivityType.Playing, name: "Content Warning" },
  { type: ActivityType.Playing, name: "osu!" },
  { type: ActivityType.Playing, name: "Geometry Dash" },
  { type: ActivityType.Playing, name: "Beat Saber" },
  { type: ActivityType.Playing, name: "Cookie Clicker" },
  { type: ActivityType.Playing, name: "Inscryption" },
  { type: ActivityType.Playing, name: "Hades II" },
  { type: ActivityType.Playing, name: "The Binding of Isaac" },
  { type: ActivityType.Playing, name: "Dead by Daylight" },
  { type: ActivityType.Playing, name: "Left 4 Dead 2" },
  { type: ActivityType.Playing, name: "Payday 2" },
  { type: ActivityType.Playing, name: "Escape from Tarkov" },
  { type: ActivityType.Playing, name: "Hunt: Showdown" },
  { type: ActivityType.Playing, name: "The Forest" },
  { type: ActivityType.Playing, name: "Sons of the Forest" },
  { type: ActivityType.Playing, name: "Green Hell" },
  { type: ActivityType.Playing, name: "Subnautica" },
  { type: ActivityType.Playing, name: "Raft" },
  { type: ActivityType.Playing, name: "Core Keeper" },
  { type: ActivityType.Playing, name: "Don't Starve" },
  { type: ActivityType.Playing, name: "Oxygen Not Included" },
  { type: ActivityType.Playing, name: "Kerbal Space Program" },
  { type: ActivityType.Playing, name: "Euro Truck Simulator 2" },
  { type: ActivityType.Playing, name: "Microsoft Flight Simulator" },
  { type: ActivityType.Playing, name: "Forza Horizon" },
  { type: ActivityType.Playing, name: "EA Sports FC" },
  { type: ActivityType.Playing, name: "NBA 2K" },
  { type: ActivityType.Playing, name: "Wii Sports, spirituellement" },
  { type: ActivityType.Playing, name: "Animal Crossing" },
  { type: ActivityType.Playing, name: "Splatoon 3" },
  { type: ActivityType.Playing, name: "Tears of the Kingdom" },
  { type: ActivityType.Playing, name: "Breath of the Wild" },
  { type: ActivityType.Playing, name: "Super Mario Odyssey" },
  { type: ActivityType.Playing, name: "Kirby" },
  { type: ActivityType.Playing, name: "Metroid" },
  { type: ActivityType.Playing, name: "Pokémon Violet" },
  { type: ActivityType.Playing, name: "Pokémon GO, sans bouger" },
  { type: ActivityType.Playing, name: "Genshin Impact" },
  { type: ActivityType.Playing, name: "Honkai: Star Rail" },
  { type: ActivityType.Playing, name: "Zenless Zone Zero" },
  { type: ActivityType.Playing, name: "Clash Royale" },
  { type: ActivityType.Playing, name: "Brawl Stars" },
  { type: ActivityType.Playing, name: "Clash of Clans" },
  { type: ActivityType.Playing, name: "League of Legends, encore une partie" },
  { type: ActivityType.Playing, name: "TFT" },
  { type: ActivityType.Playing, name: "Teamfight Tactics" },
  { type: ActivityType.Playing, name: "Wild Rift" },
  { type: ActivityType.Playing, name: "Mobile Legends" },
  { type: ActivityType.Playing, name: "Arena Breakout" },
  { type: ActivityType.Playing, name: "Delta Force" },
  { type: ActivityType.Playing, name: "Battlefield" },
  { type: ActivityType.Playing, name: "Halo Infinite" },
  { type: ActivityType.Playing, name: "Doom" },
  { type: ActivityType.Playing, name: "Ultrakill" },
  { type: ActivityType.Playing, name: "Risk of Rain 2" },
  { type: ActivityType.Playing, name: "Dead Cells" },
  { type: ActivityType.Playing, name: "Blasphemous" },
  { type: ActivityType.Playing, name: "Nine Sols" },
  { type: ActivityType.Playing, name: "Ori" },
  { type: ActivityType.Playing, name: "Cuphead" },
  { type: ActivityType.Playing, name: "It Takes Two, encore" },
  { type: ActivityType.Playing, name: "Overcooked 2" },
  { type: ActivityType.Playing, name: "Moving Out" },
  { type: ActivityType.Playing, name: "PlateUp!" },
  { type: ActivityType.Playing, name: "Tabletop Simulator" },
  { type: ActivityType.Playing, name: "Codenames" },
  { type: ActivityType.Playing, name: "Among Us, en delay" },
  { type: ActivityType.Playing, name: "Town of Salem" },
  { type: ActivityType.Playing, name: "Goose Goose Duck" },
  { type: ActivityType.Playing, name: "Project Zomboid" },
  { type: ActivityType.Playing, name: "7 Days to Die" },
  { type: ActivityType.Playing, name: "DayZ" },
  { type: ActivityType.Playing, name: "SCUM" },
  { type: ActivityType.Playing, name: "The Cycle: Frontier, dans ma tête" },
  { type: ActivityType.Playing, name: "War Thunder" },
  { type: ActivityType.Playing, name: "World of Tanks" },
  { type: ActivityType.Playing, name: "World of Warships" },
  { type: ActivityType.Playing, name: "Elite Dangerous" },
  { type: ActivityType.Playing, name: "Star Citizen, un jour" },
  { type: ActivityType.Playing, name: "Dune: Awakening" },
  { type: ActivityType.Playing, name: "Once Human" },
  { type: ActivityType.Playing, name: "Throne and Liberty" },
  { type: ActivityType.Playing, name: "Lost Ark" },
  { type: ActivityType.Playing, name: "New World" },
  { type: ActivityType.Playing, name: "Guild Wars 2" },
  { type: ActivityType.Playing, name: "The Elder Scrolls Online" },
  { type: ActivityType.Playing, name: "Destiny 2, encore une saison" },
  { type: ActivityType.Playing, name: "Warframe, encore un farm" },
  { type: ActivityType.Playing, name: "Monster Hunter, encore un hunt" },
  { type: ActivityType.Playing, name: "un jeu Unity du itch.io" },
  { type: ActivityType.Playing, name: "un jam game de 48h" },
  { type: ActivityType.Playing, name: "un jeu que j'ai installé hier" },
  { type: ActivityType.Playing, name: "un jeu que je désinstalle demain" },
  { type: ActivityType.Playing, name: "le tutoriel, toujours" },
  { type: ActivityType.Playing, name: "le menu principal" },
  { type: ActivityType.Playing, name: "les paramètres graphiques" },
  { type: ActivityType.Playing, name: "le character creator depuis 40 min" },
  { type: ActivityType.Playing, name: "le même boss depuis 2h" },
  { type: ActivityType.Playing, name: "la même quête depuis 3 jours" },
  { type: ActivityType.Playing, name: "une run permadeath déjà morte" },
  { type: ActivityType.Playing, name: "une partie classée que je regretterai" },

  // ── Regarde ─────────────────────────────────────────────────────────
  { type: ActivityType.Watching, name: "un tuto cuisine" },
  { type: ActivityType.Watching, name: "la boutique Fortnite" },
  { type: ActivityType.Watching, name: "un speedrun" },
  { type: ActivityType.Watching, name: "les clips du salon" },
  { type: ActivityType.Watching, name: "un film que tout le monde a déjà vu" },
  { type: ActivityType.Watching, name: "un anime à 3h du mat" },
  { type: ActivityType.Watching, name: "un épisode que j'ai déjà vu" },
  { type: ActivityType.Watching, name: "un trailer de 4 minutes" },
  { type: ActivityType.Watching, name: "un trailer de 40 secondes" },
  { type: ActivityType.Watching, name: "un State of Play" },
  { type: ActivityType.Watching, name: "un Direct Nintendo" },
  { type: ActivityType.Watching, name: "un Xbox Showcase" },
  { type: ActivityType.Watching, name: "un Summer Game Fest" },
  { type: ActivityType.Watching, name: "un Twitch AFK" },
  { type: ActivityType.Watching, name: "un live sans son" },
  { type: ActivityType.Watching, name: "un live avec trop de son" },
  { type: ActivityType.Watching, name: "un recap YouTube" },
  { type: ActivityType.Watching, name: "un lore video de 2h" },
  { type: ActivityType.Watching, name: "un tuto que je ne suivrai pas" },
  { type: ActivityType.Watching, name: "un tuto réparation PC" },
  { type: ActivityType.Watching, name: "un tuto cuisine que je ne ferai pas" },
  { type: ActivityType.Watching, name: "un tuto Minecraft redstone" },
  { type: ActivityType.Watching, name: "un tuto build Fortnite" },
  { type: ActivityType.Watching, name: "un tuto aim" },
  { type: ActivityType.Watching, name: "un tuto que j'ai déjà ouvert 12 fois" },
  { type: ActivityType.Watching, name: "un fail compilation" },
  { type: ActivityType.Watching, name: "un clip TikTok en boucle" },
  { type: ActivityType.Watching, name: "un documentaire animaux" },
  { type: ActivityType.Watching, name: "un documentaire espace" },
  { type: ActivityType.Watching, name: "un documentaire histoire" },
  { type: ActivityType.Watching, name: "un film d'horreur, lumière allumée" },
  { type: ActivityType.Watching, name: "un film nul, volontairement" },
  { type: ActivityType.Watching, name: "un film trop bien, en silence" },
  { type: ActivityType.Watching, name: "une série que je binge" },
  { type: ActivityType.Watching, name: "une série que j'ai drop" },
  { type: ActivityType.Watching, name: "une série que tout le monde spoil" },
  { type: ActivityType.Watching, name: "les crédits d'un jeu" },
  { type: ActivityType.Watching, name: "un écran de chargement" },
  { type: ActivityType.Watching, name: "un changelog" },
  { type: ActivityType.Watching, name: "un patch note" },
  { type: ActivityType.Watching, name: "un deal Instant Gaming" },
  { type: ActivityType.Watching, name: "les soldes Steam" },
  { type: ActivityType.Watching, name: "les jeux gratuits Epic" },
  { type: ActivityType.Watching, name: "le Game Pass" },
  { type: ActivityType.Watching, name: "un comparatif GPU" },
  { type: ActivityType.Watching, name: "un unboxing" },
  { type: ActivityType.Watching, name: "un setup tour" },
  { type: ActivityType.Watching, name: "un speedbuild" },
  { type: ActivityType.Watching, name: "un no-hit run" },
  { type: ActivityType.Watching, name: "un any%" },
  { type: ActivityType.Watching, name: "un 100%" },
  { type: ActivityType.Watching, name: "un glitch compilation" },
  { type: ActivityType.Watching, name: "un Easter egg" },
  { type: ActivityType.Watching, name: "un hidden cutscene" },
  { type: ActivityType.Watching, name: "un ending secret" },
  { type: ActivityType.Watching, name: "un let's play de 2016" },
  { type: ActivityType.Watching, name: "un vieux Machinima" },
  { type: ActivityType.Watching, name: "un match e-sport" },
  { type: ActivityType.Watching, name: "un tournoi amateur" },
  { type: ActivityType.Watching, name: "un 1v1 dans le salon" },
  { type: ActivityType.Watching, name: "les notifs arriver" },
  { type: ActivityType.Watching, name: "le salon suggestions" },
  { type: ActivityType.Watching, name: "le salon général" },
  { type: ActivityType.Watching, name: "le salon clips" },
  { type: ActivityType.Watching, name: "un sondage du serveur" },
  { type: ActivityType.Watching, name: "un thread trop long" },
  { type: ActivityType.Watching, name: "un wiki Fextralife" },
  { type: ActivityType.Watching, name: "un wiki Fandom" },
  { type: ActivityType.Watching, name: "un Google Doc de build" },
  { type: ActivityType.Watching, name: "un spreadsheet" },
  { type: ActivityType.Watching, name: "un Reddit argument" },
  { type: ActivityType.Watching, name: "un Twitter drama" },
  { type: ActivityType.Watching, name: "un leak douteux" },
  { type: ActivityType.Watching, name: "un leak probablement faux" },
  { type: ActivityType.Watching, name: "un leak probablement vrai" },
  { type: ActivityType.Watching, name: "la roadmap" },
  { type: ActivityType.Watching, name: "la météo, comme un adulte" },
  { type: ActivityType.Watching, name: "un tuto plantes" },
  { type: ActivityType.Watching, name: "un tuto nœuds" },
  { type: ActivityType.Watching, name: "un tuto café" },
  { type: ActivityType.Watching, name: "un tuto pain" },
  { type: ActivityType.Watching, name: "un tuto origami" },
  { type: ActivityType.Watching, name: "un tuto dessin" },
  { type: ActivityType.Watching, name: "un tuto piano" },
  { type: ActivityType.Watching, name: "un tuto que je mets en 2x" },
  { type: ActivityType.Watching, name: "un tuto que je mets en 0.75x" },
  { type: ActivityType.Watching, name: "la même pub YouTube" },
  { type: ActivityType.Watching, name: "un ASMR clavier" },
  { type: ActivityType.Watching, name: "un aquarium en 4K" },
  { type: ActivityType.Watching, name: "un train en caméra frontale" },
  { type: ActivityType.Watching, name: "un feu de cheminée" },
  { type: ActivityType.Watching, name: "la pluie par la fenêtre" },
  { type: ActivityType.Watching, name: "rien, vraiment rien" },
  { type: ActivityType.Watching, name: "un recap Fortnite" },
  { type: ActivityType.Watching, name: "un recap Minecraft" },
  { type: ActivityType.Watching, name: "un recap LoL" },
  { type: ActivityType.Watching, name: "un recap Valorant" },
  { type: ActivityType.Watching, name: "un VOD de 8 heures" },
  { type: ActivityType.Watching, name: "un highlight de 12 secondes" },
  { type: ActivityType.Watching, name: "un ranking de 50 jeux" },
  { type: ActivityType.Watching, name: "un tier list" },
  { type: ActivityType.Watching, name: "un iceberg" },
  { type: ActivityType.Watching, name: "un iceberg trop profond" },
  { type: ActivityType.Watching, name: "un video essay de 45 min" },
  { type: ActivityType.Watching, name: "un MrBeast, malgré moi" },
  { type: ActivityType.Watching, name: "un short que j'ai déjà vu" },
  { type: ActivityType.Watching, name: "un reel identique au short" },
  { type: ActivityType.Watching, name: "un stream IRL" },
  { type: ActivityType.Watching, name: "un just chatting" },
  { type: ActivityType.Watching, name: "un react" },
  { type: ActivityType.Watching, name: "un react du react" },
  { type: ActivityType.Watching, name: "un podcast filmé" },
  { type: ActivityType.Watching, name: "un debate Twitter devenu YouTube" },
  { type: ActivityType.Watching, name: "un AMA Reddit" },
  { type: ActivityType.Watching, name: "un AMA que personne n'a demandé" },
  { type: ActivityType.Watching, name: "un patch cam" },
  { type: ActivityType.Watching, name: "un drop calendar" },
  { type: ActivityType.Watching, name: "un shop reset" },
  { type: ActivityType.Watching, name: "un item shop" },
  { type: ActivityType.Watching, name: "un battle pass" },
  { type: ActivityType.Watching, name: "un event in-game" },
  { type: ActivityType.Watching, name: "un countdown d'event" },
  { type: ActivityType.Watching, name: "un teaser de 8 secondes" },
  { type: ActivityType.Watching, name: "un teaser de teaser" },
  { type: ActivityType.Watching, name: "un cinématique en 4K" },
  { type: ActivityType.Watching, name: "un gameplay leak" },
  { type: ActivityType.Watching, name: "un benchmark 4K" },
  { type: ActivityType.Watching, name: "un test 1080p low" },
  { type: ActivityType.Watching, name: "un comparatif SSD" },
  { type: ActivityType.Watching, name: "un unbox clavier" },
  { type: ActivityType.Watching, name: "un cable management" },
  { type: ActivityType.Watching, name: "un RGB trop RGB" },
  { type: ActivityType.Watching, name: "un aquarium Discord" },
  { type: ActivityType.Watching, name: "un chat qui marche sur un clavier" },
  { type: ActivityType.Watching, name: "un chat qui s'en fiche" },
  { type: ActivityType.Watching, name: "la même cutscene skippée trop tard" },
  { type: ActivityType.Watching, name: "les achievements Steam" },
  { type: ActivityType.Watching, name: "les heures de jeu de quelqu'un" },
  { type: ActivityType.Watching, name: "un profil Steam trop honnête" },
  { type: ActivityType.Watching, name: "un backlog Steam trop réel" },
  { type: ActivityType.Watching, name: "un review bomb" },
  { type: ActivityType.Watching, name: "un Metacritic" },
  { type: ActivityType.Watching, name: "un OpenCritic" },
  { type: ActivityType.Watching, name: "un Fandom trop spoil" },
  { type: ActivityType.Watching, name: "un wiki trop vide" },
  { type: ActivityType.Watching, name: "un Google Maps trop zoomé" },
  { type: ActivityType.Watching, name: "un Street View random" },
  { type: ActivityType.Watching, name: "un timelapse de nuages" },
  { type: ActivityType.Watching, name: "un live cam aéroport" },
  { type: ActivityType.Watching, name: "un live cam mer" },
  { type: ActivityType.Watching, name: "un match que tout le monde spoil déjà" },
  { type: ActivityType.Watching, name: "un ending que je savais déjà" },
  { type: ActivityType.Watching, name: "un générique trop long" },
  { type: ActivityType.Watching, name: "un after-credits, au cas où" },

  // ── Écoute ──────────────────────────────────────────────────────────
  { type: ActivityType.Listening, name: "le vocal" },
  { type: ActivityType.Listening, name: "la playlist" },
  { type: ActivityType.Listening, name: "vos débats" },
  { type: ActivityType.Listening, name: "un podcast random" },
  { type: ActivityType.Listening, name: "un podcast histoire" },
  { type: ActivityType.Listening, name: "un podcast science" },
  { type: ActivityType.Listening, name: "un podcast jeux vidéo" },
  { type: ActivityType.Listening, name: "un podcast true crime" },
  { type: ActivityType.Listening, name: "un podcast cuisine" },
  { type: ActivityType.Listening, name: "un podcast que je relance 3 fois" },
  { type: ActivityType.Listening, name: "la OST d'un jeu" },
  { type: ActivityType.Listening, name: "la OST de Minecraft" },
  { type: ActivityType.Listening, name: "la OST d'Undertale" },
  { type: ActivityType.Listening, name: "la OST de Zelda" },
  { type: ActivityType.Listening, name: "la OST de Celeste" },
  { type: ActivityType.Listening, name: "un lofi beats" },
  { type: ActivityType.Listening, name: "un lofi hip hop" },
  { type: ActivityType.Listening, name: "du jazz à 1h" },
  { type: ActivityType.Listening, name: "du classique, sans raison" },
  { type: ActivityType.Listening, name: "du métal, avec raison" },
  { type: ActivityType.Listening, name: "de la synthwave" },
  { type: ActivityType.Listening, name: "de la city pop" },
  { type: ActivityType.Listening, name: "de la musique de générique" },
  { type: ActivityType.Listening, name: "un album entier" },
  { type: ActivityType.Listening, name: "la même chanson en boucle" },
  { type: ActivityType.Listening, name: "une playlist de 14h" },
  { type: ActivityType.Listening, name: "une playlist de 4 titres" },
  { type: ActivityType.Listening, name: "Spotify Discover Weekly" },
  { type: ActivityType.Listening, name: "une radio lointaine" },
  { type: ActivityType.Listening, name: "la pluie" },
  { type: ActivityType.Listening, name: "un orage" },
  { type: ActivityType.Listening, name: "un ventilateur" },
  { type: ActivityType.Listening, name: "un clavier mécanique" },
  { type: ActivityType.Listening, name: "un ASMR" },
  { type: ActivityType.Listening, name: "un audiobook" },
  { type: ActivityType.Listening, name: "un livre audio trop lent" },
  { type: ActivityType.Listening, name: "vos théories de lore" },
  { type: ActivityType.Listening, name: "vos excuses de ragequit" },
  { type: ActivityType.Listening, name: "vos plans de raid" },
  { type: ActivityType.Listening, name: "vos builds cassés" },
  { type: ActivityType.Listening, name: "vos spoilers accidentels" },
  { type: ActivityType.Listening, name: "vos débats hardware" },
  { type: ActivityType.Listening, name: "vos débats PC vs console" },
  { type: ActivityType.Listening, name: "vos débats clavier vs manette" },
  { type: ActivityType.Listening, name: "le salon musique" },
  { type: ActivityType.Listening, name: "le salon no-micro" },
  { type: ActivityType.Listening, name: "un vocal vide" },
  { type: ActivityType.Listening, name: "un vocal trop chargé" },
  { type: ActivityType.Listening, name: "quelqu'un qui mange dans le vocal" },
  { type: ActivityType.Listening, name: "quelqu'un qui respire trop près du micro" },
  { type: ActivityType.Listening, name: "un echo test" },
  { type: ActivityType.Listening, name: "un bruit de notif" },
  { type: ActivityType.Listening, name: "un bruit de Discord" },
  { type: ActivityType.Listening, name: "le silence, enfin" },
  { type: ActivityType.Listening, name: "rien, casque sur les oreilles" },
  { type: ActivityType.Listening, name: "une pub que je peux pas skip" },
  { type: ActivityType.Listening, name: "un sample de 2003" },
  { type: ActivityType.Listening, name: "un remix douteux" },
  { type: ActivityType.Listening, name: "un mashup de génériques" },
  { type: ActivityType.Listening, name: "un concert live" },
  { type: ActivityType.Listening, name: "un set à 160 BPM" },
  { type: ActivityType.Listening, name: "un set à 80 BPM" },
  { type: ActivityType.Listening, name: "une BO de film" },
  { type: ActivityType.Listening, name: "une BO d'anime" },
  { type: ActivityType.Listening, name: "une chanson que je connais pas" },
  { type: ActivityType.Listening, name: "une chanson que je connais trop" },
  { type: ActivityType.Listening, name: "vos playlists partagées" },
  { type: ActivityType.Listening, name: "le bruit blanc" },
  { type: ActivityType.Listening, name: "du brown noise" },
  { type: ActivityType.Listening, name: "un café en fond" },
  { type: ActivityType.Listening, name: "une ville la nuit" },
  { type: ActivityType.Listening, name: "un marché lointain" },
  { type: ActivityType.Listening, name: "des oiseaux, c'est l'heure" },
  { type: ActivityType.Listening, name: "la OST de Hollow Knight" },
  { type: ActivityType.Listening, name: "la OST de Hades" },
  { type: ActivityType.Listening, name: "la OST de Stardew Valley" },
  { type: ActivityType.Listening, name: "la OST de Cyberpunk" },
  { type: ActivityType.Listening, name: "la OST de Persona" },
  { type: ActivityType.Listening, name: "la OST de NieR" },
  { type: ActivityType.Listening, name: "du piano lo-fi" },
  { type: ActivityType.Listening, name: "du boom bap" },
  { type: ActivityType.Listening, name: "du drill, trop fort" },
  { type: ActivityType.Listening, name: "du rap français" },
  { type: ActivityType.Listening, name: "du rap US de 2012" },
  { type: ActivityType.Listening, name: "une chanson de générique Nintendo" },
  { type: ActivityType.Listening, name: "une chanson que j'ai shazam 4 fois" },
  { type: ActivityType.Listening, name: "une radio lofi 24/7" },
  { type: ActivityType.Listening, name: "une radio jazz 24/7" },
  { type: ActivityType.Listening, name: "une radio que je comprends pas" },
  { type: ActivityType.Listening, name: "un vinyl crackle" },
  { type: ActivityType.Listening, name: "un vinyle trop usé" },
  { type: ActivityType.Listening, name: "un cassette hiss" },
  { type: ActivityType.Listening, name: "un 8-bit cover" },
  { type: ActivityType.Listening, name: "un orchestral cover" },
  { type: ActivityType.Listening, name: "un metal cover d'une chanson calme" },
  { type: ActivityType.Listening, name: "un calme cover d'une chanson metal" },
  { type: ActivityType.Listening, name: "un podcast tech" },
  { type: ActivityType.Listening, name: "un podcast cinéma" },
  { type: ActivityType.Listening, name: "un podcast foot" },
  { type: ActivityType.Listening, name: "un podcast que je mets en 1.5x" },
  { type: ActivityType.Listening, name: "un podcast que je mets en 0.8x" },
  { type: ActivityType.Listening, name: "vos ranked rage" },
  { type: ActivityType.Listening, name: "vos callouts" },
  { type: ActivityType.Listening, name: "vos excuses de lag" },
  { type: ActivityType.Listening, name: "vos histoires de loot" },
  { type: ActivityType.Listening, name: "vos théories Deltarune" },
  { type: ActivityType.Listening, name: "vos théories Undertale" },
  { type: ActivityType.Listening, name: "vos théories Minecraft" },
  { type: ActivityType.Listening, name: "le bruit d'un PC qui souffre" },
  { type: ActivityType.Listening, name: "le bruit d'un GPU trop chaud" },
  { type: ActivityType.Listening, name: "le bruit d'une imprimante 3D" },
  { type: ActivityType.Listening, name: "le bruit d'un micro-ondes" },
  { type: ActivityType.Listening, name: "le bruit d'une machine à laver" },
  { type: ActivityType.Listening, name: "le bruit de la rue" },
  { type: ActivityType.Listening, name: "le bruit de la pluie sur un toit" },
  { type: ActivityType.Listening, name: "le bruit d'un train" },
  { type: ActivityType.Listening, name: "le bruit d'un café trop plein" },
  { type: ActivityType.Listening, name: "rien, vraiment, casque off" },

  // ── En compétition dans ─────────────────────────────────────────────
  { type: ActivityType.Competing, name: "un quiz" },
  { type: ActivityType.Competing, name: "un 1v1" },
  { type: ActivityType.Competing, name: "un 2v2" },
  { type: ActivityType.Competing, name: "un FFA" },
  { type: ActivityType.Competing, name: "un tournoi salon" },
  { type: ActivityType.Competing, name: "un tournoi Minecraft" },
  { type: ActivityType.Competing, name: "un tournoi Fortnite" },
  { type: ActivityType.Competing, name: "un tournoi Mario Kart" },
  { type: ActivityType.Competing, name: "un tournoi Smash" },
  { type: ActivityType.Competing, name: "un tournoi just for fun" },
  { type: ActivityType.Competing, name: "un ranked que je vais lose" },
  { type: ActivityType.Competing, name: "un ranked que je vais win" },
  { type: ActivityType.Competing, name: "un placement match" },
  { type: ActivityType.Competing, name: "un custom" },
  { type: ActivityType.Competing, name: "un scrim" },
  { type: ActivityType.Competing, name: "un clutch" },
  { type: ActivityType.Competing, name: "un overtime" },
  { type: ActivityType.Competing, name: "un best of 3" },
  { type: ActivityType.Competing, name: "un best of 5" },
  { type: ActivityType.Competing, name: "un speedrun amateur" },
  { type: ActivityType.Competing, name: "un no-hit challenge" },
  { type: ActivityType.Competing, name: "un no-death run" },
  { type: ActivityType.Competing, name: "un 100% run" },
  { type: ActivityType.Competing, name: "un any% run" },
  { type: ActivityType.Competing, name: "un boss rush" },
  { type: ActivityType.Competing, name: "un raid" },
  { type: ActivityType.Competing, name: "un donjon" },
  { type: ActivityType.Competing, name: "un nightfall" },
  { type: ActivityType.Competing, name: "un event limité" },
  { type: ActivityType.Competing, name: "un battle pass grind" },
  { type: ActivityType.Competing, name: "un weekly" },
  { type: ActivityType.Competing, name: "un daily que j'ai oublié" },
  { type: ActivityType.Competing, name: "un contest de builds" },
  { type: ActivityType.Competing, name: "un contest de skins" },
  { type: ActivityType.Competing, name: "un contest de clips" },
  { type: ActivityType.Competing, name: "un contest de memes" },
  { type: ActivityType.Competing, name: "un kahoot" },
  { type: ActivityType.Competing, name: "un trivia" },
  { type: ActivityType.Competing, name: "un blind test" },
  { type: ActivityType.Competing, name: "un jeu des 7 différences" },
  { type: ActivityType.Competing, name: "un pierre-feuille-ciseaux" },
  { type: ActivityType.Competing, name: "un pile ou face" },
  { type: ActivityType.Competing, name: "un duel d'arguments" },
  { type: ActivityType.Competing, name: "un débat PC vs console" },
  { type: ActivityType.Competing, name: "un débat clavier vs manette" },
  { type: ActivityType.Competing, name: "un débat meilleur jeu 2024" },
  { type: ActivityType.Competing, name: "un débat meilleur jeu 2025" },
  { type: ActivityType.Competing, name: "un débat meilleur jeu 2026" },
  { type: ActivityType.Competing, name: "un débat meilleur fromage" },
  { type: ActivityType.Competing, name: "un débat meilleur café" },
  { type: ActivityType.Competing, name: "un débat meilleur pizza" },
  { type: ActivityType.Competing, name: "un débat meilleur starter Pokémon" },
  { type: ActivityType.Competing, name: "un débat meilleure classe" },
  { type: ActivityType.Competing, name: "un débat meilleur arme" },
  { type: ActivityType.Competing, name: "un débat meilleur ending" },
  { type: ActivityType.Competing, name: "un débat meilleur OST" },
  { type: ActivityType.Competing, name: "une course de crafts" },
  { type: ActivityType.Competing, name: "une course de farms" },
  { type: ActivityType.Competing, name: "une course de speedrun" },
  { type: ActivityType.Competing, name: "une course à la boutique" },
  { type: ActivityType.Competing, name: "une course au last pickup" },
  { type: ActivityType.Competing, name: "une course au clutch" },
  { type: ActivityType.Competing, name: "une course au drop" },
  { type: ActivityType.Competing, name: "une course au GG" },
  { type: ActivityType.Competing, name: "le dernier café" },
  { type: ActivityType.Competing, name: "le dernier croissant" },
  { type: ActivityType.Competing, name: "le last slot du vocal" },
  { type: ActivityType.Competing, name: "le last laugh" },
  { type: ActivityType.Competing, name: "le last word" },
  { type: ActivityType.Competing, name: "le ping le plus bas" },
  { type: ActivityType.Competing, name: "le K/D le plus honteux" },
  { type: ActivityType.Competing, name: "le clutch le plus sale" },
  { type: ActivityType.Competing, name: "le GG le plus rapide" },
  { type: ActivityType.Competing, name: "le ragequit le plus élégant" },
  { type: ActivityType.Competing, name: "un tournoi Valorant" },
  { type: ActivityType.Competing, name: "un tournoi LoL" },
  { type: ActivityType.Competing, name: "un tournoi Rocket League" },
  { type: ActivityType.Competing, name: "un tournoi CS2" },
  { type: ActivityType.Competing, name: "un tournoi Overwatch" },
  { type: ActivityType.Competing, name: "un tournoi Smash amateur" },
  { type: ActivityType.Competing, name: "un tournoi GeoGuessr" },
  { type: ActivityType.Competing, name: "un tournoi osu!" },
  { type: ActivityType.Competing, name: "un 1v1 Minecraft" },
  { type: ActivityType.Competing, name: "un 1v1 Fortnite" },
  { type: ActivityType.Competing, name: "un 1v1 Mario Kart" },
  { type: ActivityType.Competing, name: "un UHC" },
  { type: ActivityType.Competing, name: "un manhunt" },
  { type: ActivityType.Competing, name: "un speedrun any%" },
  { type: ActivityType.Competing, name: "un speedrun 100%" },
  { type: ActivityType.Competing, name: "un challenge no-hit" },
  { type: ActivityType.Competing, name: "un challenge sl1" },
  { type: ActivityType.Competing, name: "un challenge nuzlocke" },
  { type: ActivityType.Competing, name: "un challenge hardcore" },
  { type: ActivityType.Competing, name: "un contest de redstone" },
  { type: ActivityType.Competing, name: "un contest de builds Fortnite" },
  { type: ActivityType.Competing, name: "un contest de screenshots" },
  { type: ActivityType.Competing, name: "un contest de fanart" },
  { type: ActivityType.Competing, name: "un kahoot trop tendu" },
  { type: ActivityType.Competing, name: "un blind test trop dur" },
  { type: ActivityType.Competing, name: "un quiz lore" },
  { type: ActivityType.Competing, name: "un quiz OST" },
  { type: ActivityType.Competing, name: "un quiz Pokémon" },
  { type: ActivityType.Competing, name: "un quiz films" },
  { type: ActivityType.Competing, name: "un débat meilleur boss" },
  { type: ActivityType.Competing, name: "un débat meilleur DLC" },
  { type: ActivityType.Competing, name: "un débat meilleur indé" },
  { type: ActivityType.Competing, name: "un débat meilleur multi" },
  { type: ActivityType.Competing, name: "un débat meilleur solo" },
  { type: ActivityType.Competing, name: "un débat meilleur souls" },
  { type: ActivityType.Competing, name: "un débat meilleur Battle Pass" },
  { type: ActivityType.Competing, name: "un débat meilleur snack" },
  { type: ActivityType.Competing, name: "un débat meilleur soda" },
  { type: ActivityType.Competing, name: "un débat meilleur heure de game" },
  { type: ActivityType.Competing, name: "le last kill" },
  { type: ActivityType.Competing, name: "le last round" },
  { type: ActivityType.Competing, name: "le last stock" },
  { type: ActivityType.Competing, name: "le last checkpoint" },
  { type: ActivityType.Competing, name: "le ping le plus honteux" },
  { type: ActivityType.Competing, name: "le clutch 1v5" },
  { type: ActivityType.Competing, name: "le GG le plus sarcastique" },
  { type: ActivityType.Competing, name: "le dodge le plus propre" },
];

const ROTATE_MS = 8 * 60 * 1000;

let lastIndex = -1;
let current = JOHN_ACTIVITIES[0];
let started = false;
let rotateTimer: ReturnType<typeof setInterval> | null = null;
let presenceStatus: PresenceStatusData = "online";

export function pickNextActivity(
  list: { name: string; type: ActivityType }[] = JOHN_ACTIVITIES,
  previous = lastIndex,
): { activity: { name: string; type: ActivityType }; index: number } {
  if (list.length === 0) {
    return { activity: { name: "Discord", type: ActivityType.Playing }, index: 0 };
  }
  if (list.length === 1) return { activity: list[0], index: 0 };
  let index = previous;
  while (index === previous) {
    index = Math.floor(Math.random() * list.length);
  }
  return { activity: list[index], index };
}

export function getCurrentActivity(): { name: string; type: ActivityType } {
  return current;
}

export async function applyCurrentPresence(client: Client): Promise<void> {
  if (!client.user) return;
  try {
    await client.user.setPresence({
      status: presenceStatus,
      activities: [{ name: current.name, type: current.type }],
    });
    savePresence({
      status: presenceStatus,
      activities: [{ name: current.name, type: current.type }],
    });
  } catch (err) {
    logger.warn(`[Presence] Maj impossible: ${err instanceof Error ? err.message : String(err)}`);
  }
}

async function rotate(client: Client): Promise<void> {
  const next = pickNextActivity();
  lastIndex = next.index;
  current = next.activity;
  await applyCurrentPresence(client);
  logger.info(`[Presence] ${activityVerb(current.type)} ${current.name}`);
}

function activityVerb(type: ActivityType): string {
  switch (type) {
    case ActivityType.Playing:
      return "Joue à";
    case ActivityType.Listening:
      return "Écoute";
    case ActivityType.Watching:
      return "Regarde";
    case ActivityType.Competing:
      return "Fait";
    default:
      return "Fait";
  }
}

export function setPresenceStatus(status: PresenceStatusData): void {
  presenceStatus = status;
}

export function startPresenceRotator(client: Client): void {
  if (started) return;
  started = true;
  void rotate(client);
  rotateTimer = setInterval(() => {
    void rotate(client);
  }, ROTATE_MS);
  if (rotateTimer.unref) rotateTimer.unref();
  logger.info("[Presence] Rotation toutes les 8 min");
}

export function stopPresenceRotator(): void {
  if (rotateTimer) {
    clearInterval(rotateTimer);
    rotateTimer = null;
  }
  started = false;
}

export async function syncBotDescription(client: Client): Promise<void> {
  try {
    const app = await client.application?.fetch();
    if (app) {
      const tags = [...BOT_TAGS];
      const currentTags = [...(app.tags ?? [])];
      const descOk = (app.description ?? "") === BOT_DESCRIPTION;
      const tagsOk = currentTags.join("|") === tags.join("|");
      if (!descOk || !tagsOk) {
        await app.edit({ description: BOT_DESCRIPTION, tags });
        logger.info("[Profile] Fiche Discord mise à jour");
      }
    }
  } catch (err) {
    logger.warn(
      `[Profile] Description non mise à jour: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  const guildId = config.guildId;
  if (!guildId) return;
  try {
    const guild =
      client.guilds.cache.get(guildId) ?? (await client.guilds.fetch(guildId).catch(() => null));
    if (!guild) return;
    const me = guild.members.me ?? (await guild.members.fetchMe().catch(() => null));
    if (me && me.nickname !== "John") {
      await me.setNickname("John");
      logger.info("[Profile] Surnom serveur: John");
    }
  } catch (err) {
    logger.warn(
      `[Profile] Surnom non mis à jour: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}
