/**
 * selfLearner.ts — Auto-apprentissage continu
 *
 * Le bot génère des questions sur des sujets variés, y répond via des sources
 * gratuites (Wikipédia, Wiktionnaire) et stocke les Q&A dans Obsidian.
 * Au fil du temps, le vault se remplit de connaissances pré-construites.
 *
 * Quand un utilisateur pose une question similaire, le bot trouve la Q&A
 * dans Obsidian et répond SANS appeler l'API payante.
 */

import logger from "../utils/logger.js";
import { saveQA, searchQA } from "./obsidianMemory.js";

const LEARN_INTERVAL_MS = 5 * 60 * 1000; // 5 min entre chaque batch
const BATCH_SIZE = 5; // 5 Q&A par batch = ~1440 Q&A/jour
let isLearning = false;
let learnTimer: ReturnType<typeof setInterval> | null = null;

// ─── Sujets prédéfinis pour l'apprentissage ──────────────────────────────────
// Liste massive couvrant tous les domaines possibles et imaginables
const LEARN_TOPICS: { category: string; subjects: string[] }[] = [
  {
    category: "tech",
    subjects: [
      "processeur",
      "carte graphique",
      "RAM",
      "SSD",
      "disque dur",
      "carte mère",
      "alimentation PC",
      "refroidissement liquide",
      "ventirad",
      "overclocking",
      "système d'exploitation",
      "Linux",
      "Windows",
      "macOS",
      "Ubuntu",
      "Debian",
      "Arch Linux",
      "Android",
      "iOS",
      "HarmonyOS",
      "Python",
      "JavaScript",
      "TypeScript",
      "Rust",
      "C++",
      "Java",
      "Go",
      "Kotlin",
      "Swift",
      "Ruby",
      "PHP",
      "C#",
      "Dart",
      "Scala",
      "Elixir",
      "Zig",
      "Nim",
      "intelligence artificielle",
      "machine learning",
      "deep learning",
      "réseau de neurones",
      "transformer",
      "GPT",
      "LLM",
      "RAG",
      "embedding",
      "fine-tuning",
      "vision par ordinateur",
      "NLP",
      "reconnaissance vocale",
      "synthèse vocale",
      "blockchain",
      "cryptomonnaie",
      "Bitcoin",
      "Ethereum",
      "NFT",
      "DeFi",
      "smart contract",
      "cybersécurité",
      "VPN",
      "pare-feu",
      "chiffrement",
      "AES",
      "RSA",
      "TLS",
      "SSL",
      "pentest",
      "ingénierie sociale",
      "phishing",
      "ransomware",
      "malware",
      "rootkit",
      "Docker",
      "Kubernetes",
      "cloud computing",
      "AWS",
      "Azure",
      "GCP",
      "Vercel",
      "Git",
      "GitHub",
      "GitLab",
      "CI/CD",
      "DevOps",
      "SRE",
      "base de données",
      "SQL",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "Elasticsearch",
      "GraphQL",
      "REST API",
      "gRPC",
      "WebSocket",
      "WebRTC",
      "HTML",
      "CSS",
      "Tailwind",
      "React",
      "Vue",
      "Svelte",
      "Angular",
      "Next.js",
      "Nuxt",
      "Node.js",
      "Deno",
      "Bun",
      "Express",
      "Fastify",
      "NestJS",
      "Hono",
      "Raspberry Pi",
      "Arduino",
      "ESP32",
      "IoT",
      "domotique",
      "home assistant",
      "impression 3D",
      "laser cutting",
      "CAD",
      "FreeCAD",
      "Blender",
      "réseau informatique",
      "TCP/IP",
      "DNS",
      "BGP",
      "CDN",
      "load balancer",
      "virtualisation",
      "VMware",
      "Proxmox",
      "QEMU",
      "KVM",
      "shell",
      "bash",
      "powershell",
      "awk",
      "sed",
      "vim",
      "neovim",
    ],
  },
  {
    category: "science",
    subjects: [
      "photosynthèse",
      "ADN",
      "ARN",
      "évolution",
      "génétique",
      "mutation génétique",
      "gravité",
      "relativité",
      "relativité restreinte",
      "relativité générale",
      "trou noir",
      "trou de ver",
      "système solaire",
      "étoile",
      "galaxie",
      "big bang",
      "nébuleuse",
      "pulsar",
      "quasar",
      "supernova",
      "naine blanche",
      "naine brune",
      "exoplanète",
      "Mars",
      "Jupiter",
      "Saturne",
      "Vénus",
      "Mercure",
      "Uranus",
      "Neptune",
      "Lune",
      "Titan",
      "Europe",
      "ceinture d'astéroïdes",
      "comète",
      "météorite",
      "atome",
      "molécule",
      "réaction chimique",
      "tableau périodique",
      "élément chimique",
      "électricité",
      "magnétisme",
      "thermodynamique",
      "quantique",
      "physique des particules",
      "boson de Higgs",
      "quantum",
      "superposition",
      "intrication quantique",
      "volcan",
      "tremblement de terre",
      "tectonique des plaques",
      "tsunami",
      "géothermie",
      "climat",
      "météo",
      "effet de serre",
      "océan",
      "courant marin",
      "El Niño",
      "glaciation",
      "ère glaciaire",
      "permafrost",
      "dérive des continents",
      "biologie",
      "cellule",
      "mitochondrie",
      "bactérie",
      "virus",
      "prion",
      "écosystème",
      "biodiversité",
      "extinction de masse",
      "théorie de l'évolution",
      "chimie organique",
      "chimie inorganique",
      "biochimie",
      "catalyseur",
      "mathématiques",
      "algèbre",
      "géométrie",
      "trigonométrie",
      "calcul différentiel",
      "probabilités",
      "statistiques",
      "théorie des nombres",
      "topologie",
      "fractale",
      "nombre premier",
      "nombre d'or",
      "suite de Fibonacci",
      "cryptographie",
      "théorie de l'information",
      "théorie des jeux",
      "nanotechnologie",
      "biotechnologie",
      "CRISPR",
      "clonage",
      "cellules souches",
      "fission nucléaire",
      "fusion nucléaire",
      "énergie nucléaire",
      "uranium",
      "plutonium",
      "énergie solaire",
      "énergie éolienne",
      "énergie hydraulique",
      "géothermie",
      "pile à combustible",
      "hydrogène",
      "batterie lithium-ion",
    ],
  },
  {
    category: "culture",
    subjects: [
      "Renaissance",
      "Révolution française",
      "Révolution industrielle",
      "Seconde Guerre mondiale",
      "Première Guerre mondiale",
      "Guerre froide",
      "Empire romain",
      "Empire byzantin",
      "Empire ottoman",
      "Empire mongol",
      "Antiquité grecque",
      "Antiquité égyptienne",
      "Moyen Âge",
      "féodalité",
      "découverte de l'Amérique",
      "colonisation",
      "décolonisation",
      "philosophie",
      "Socrate",
      "Platon",
      "Aristote",
      "Kant",
      "Nietzsche",
      "Descartes",
      "Rousseau",
      "Voltaire",
      "Marx",
      "Sartre",
      "Camus",
      "Stoïcisme",
      "Épicurisme",
      "existentialisme",
      "phénoménologie",
      "art",
      "peinture",
      "sculpture",
      "architecture",
      "musique",
      "opéra",
      "littérature",
      "poésie",
      "théâtre",
      "cinéma",
      "photographie",
      "Renaissance italienne",
      "Baroque",
      "Romantisme",
      "Impressionnisme",
      "Cubisme",
      "Surréalisme",
      "Art abstrait",
      "Art contemporain",
      "mythologie grecque",
      "mythologie nordique",
      "mythologie égyptienne",
      "religion",
      "bouddhisme",
      "christianisme",
      "islam",
      "hindouisme",
      "judaïsme",
      "shintoïsme",
      "taoïsme",
      "confucianisme",
      "animisme",
      "Bible",
      "Coran",
      "Torah",
      "Vedas",
      "Tripitaka",
      "langues",
      "linguistique",
      "étymologie",
      "phonétique",
      "syntaxe",
      "français",
      "anglais",
      "espagnol",
      "allemand",
      "italien",
      "portugais",
      "russe",
      "chinois",
      "japonais",
      "coréen",
      "arabe",
      "hindi",
      "espéranto",
      "latin",
      "grec ancien",
      "sanskrit",
      "cuisine française",
      "cuisine italienne",
      "cuisine japonaise",
      "cuisine chinoise",
      "cuisine indienne",
      "cuisine mexicaine",
      "gastronomie",
      "œnologie",
      "mode",
      "haute couture",
      "prêt-à-porter",
      "Louis Vuitton",
      "Chanel",
      "Dior",
      "danse",
      "ballet",
      "hip-hop",
      "tango",
      "salsa",
      "danse contemporaine",
      "festival",
      "Cannes",
      "Oscars",
      "Grammy Awards",
      "Eurovision",
    ],
  },
  {
    category: "gaming",
    subjects: [
      "Helldivers",
      "Helldivers 2",
      "GTA",
      "GTA V",
      "GTA 6",
      "GTA Online",
      "Minecraft",
      "Fortnite",
      "Valorant",
      "League of Legends",
      "Counter-Strike",
      "Counter-Strike 2",
      "Dota 2",
      "Overwatch",
      "Overwatch 2",
      "Apex Legends",
      "Call of Duty",
      "Battlefield",
      "Rainbow Six Siege",
      "Elden Ring",
      "Dark Souls",
      "Bloodborne",
      "Sekiro",
      "The Witcher",
      "Cyberpunk 2077",
      "Baldur's Gate 3",
      "Skyrim",
      "Final Fantasy",
      "Final Fantasy VII",
      "Kingdom Hearts",
      "Zelda",
      "Breath of the Wild",
      "Tears of the Kingdom",
      "Mario",
      "Sonic",
      "Pokémon",
      "Metroid",
      "Donkey Kong",
      "PlayStation",
      "Xbox",
      "Nintendo Switch",
      "PC gaming",
      "Steam Deck",
      "Steam",
      "Epic Games",
      "Battle.net",
      "GOG",
      "itch.io",
      "MMORPG",
      "FPS",
      "RPG",
      "RTS",
      "battle royale",
      "MOBA",
      "roguelike",
      "metroidvania",
      "visual novel",
      "point and click",
      "speedrun",
      "esport",
      "streaming",
      "Twitch",
      "YouTube Gaming",
      "game engine",
      "Unreal Engine",
      "Unity",
      "Godot",
      "game design",
      "game developer",
      "indie game",
      "Early Access",
      "DLC",
      "microtransaction",
      "loot box",
      "battle pass",
      "cross-play",
      "ray tracing",
      "DLSS",
      "FSR",
      "PlayStation 5",
      "Xbox Series X",
      "PlayStation 4",
      "Xbox One",
      "Game Boy",
      "NES",
      "SNES",
      "Sega Genesis",
      "N64",
      "PS1",
      "PS2",
      "PS3",
      "rétrogaming",
      "émulateur",
      "ROM",
      "arcade",
    ],
  },
  {
    category: "quotidien",
    subjects: [
      "nutrition",
      "vitamine C",
      "vitamine D",
      "vitamine B12",
      "fer",
      "calcium",
      "protéine",
      "glucide",
      "lipide",
      "fibre alimentaire",
      "antioxydant",
      "régime alimentaire",
      "végétarisme",
      "végétalisme",
      "cétogène",
      "jeûne intermittent",
      "sommeil",
      "insomnie",
      "apnée du sommeil",
      "cycle circadien",
      "stress",
      "anxiété",
      "dépression",
      "burn-out",
      "méditation",
      "pleine conscience",
      "exercice physique",
      "musculation",
      "cardio",
      "yoga",
      "Pilates",
      "stretching",
      "running",
      "cyclisme",
      "natation",
      "escalade",
      "randonnée",
      "ski",
      "surf",
      "cuisine",
      "recette",
      "pâtisserie",
      "boulangerie",
      "pâtes",
      "pizza",
      "sushi",
      "jardinage",
      "plante",
      "fleur",
      "bonsaï",
      "potager",
      "compost",
      "voyage",
      "culture japonaise",
      "culture coréenne",
      "culture américaine",
      "culture chinoise",
      "culture indienne",
      "culture africaine",
      "Tokyo",
      "Paris",
      "Londres",
      "New York",
      "Séoul",
      "Bangkok",
      "Barcelone",
      "maison",
      "décoration",
      "minimalisme",
      "feng shui",
      "bricolage",
      "voiture",
      "véhicule électrique",
      "hybride",
      "Tesla",
      "vélo",
      "scooter",
      "finance personnelle",
      "budget",
      "épargne",
      "investissement",
      "bourse",
      "assurance",
      "hypothèque",
      "crédit",
      "impôt",
      "cryptomonnaie",
      "éducation",
      "école",
      "université",
      "apprentissage",
      "mémoire",
      "concentration",
      "productivité",
      "gestion du temps",
      "Pomodoro",
      "GTD",
      "Notion",
      "Obsidian",
      "santé mentale",
      "thérapie",
      "psychologie",
      "psychanalyse",
      "TCCE",
      "relation",
      "communication",
      "non-violente",
      "intelligence émotionnelle",
      "parenting",
      "enfant",
      "adolescent",
      "éducation wellington",
    ],
  },
  {
    category: "discord",
    subjects: [
      "comment bannir un membre Discord",
      "comment configurer les rôles Discord",
      "comment créer un bot Discord",
      "permissions Discord",
      "webhooks Discord",
      "salons vocaux Discord",
      "intégrations Discord",
      "Discord Nitro",
      "serveur Discord communautaire",
      "modération Discord automatisée",
      "Discord.js",
      "Discord.py",
      "slash commands Discord",
      "embeds Discord",
      "Discord API",
      "Discord OAuth2",
      "Discord bot hosting",
      "auto-mod Discord",
      "anti-raid Discord",
      "anti-spam Discord",
      "Discord tickets",
      "Discord threads",
      "Discord forums",
      "Discord stages",
      "Discord events",
      "Discord activities",
    ],
  },
  {
    category: "osint",
    subjects: [
      "recherche OSINT",
      "investigation numérique",
      "analyse de domaine",
      "WHOIS",
      "DNS lookup",
      "scan de ports",
      "empreinte digitale web",
      "réseaux sociaux investigation",
      "géolocalisation",
      "analyse de métadonnées",
      "stéganographie",
      "Maltego",
      "Shodan",
      "theHarvester",
      "SpiderFoot",
      "Google dorking",
      "Wayback Machine",
      "archive internet",
      "VPN detection",
      "proxy detection",
      "Tor",
      "dark web",
      "deep web",
      "forensic",
      "analyse de disque",
      "récupération de données",
      "ingénierie sociale",
      "phishing",
      "spear phishing",
      "vishing",
      "threat intelligence",
      "IOC",
      "APT",
      "ransomware",
      "botnet",
      "zero-day",
      "exploit",
      "CVE",
      "vulnerability scanner",
      "Nessus",
      "Burp Suite",
      "Metasploit",
      "Nmap",
      "Wireshark",
      "John the Ripper",
    ],
  },
  {
    category: "meteo",
    subjects: [
      "prévision météo",
      "nuages",
      "cumulus",
      "stratus",
      "cirrus",
      "cumulonimbus",
      "orage",
      "foudre",
      "éclair",
      "tonnerre",
      "grêle",
      "tornade",
      "ouragan",
      "cyclone",
      "typhon",
      "anticyclone",
      "dépression atmosphérique",
      "front froid",
      "front chaud",
      "front occlus",
      "humidité",
      "pression atmosphérique",
      "température",
      "point de rosée",
      "isobare",
      "isotherme",
      "vent",
      "brise",
      "mistral",
      "sirocco",
      "foehn",
      "canicule",
      "vague de froid",
      "gel",
      "neige",
      "verglas",
      "brouillard",
      "arc-en-ciel",
      "parhélie",
      "aurore boréale",
      "aurore australe",
      "satellite météo",
      "radar météo",
      "station météo",
      "anémomètre",
      "El Niño",
      "La Niña",
      "oscillation australe",
      "gulf stream",
      "réchauffement climatique",
      "changements climatiques",
      "GIEC",
      "empreinte carbone",
      "neutralité carbone",
      "transition écologique",
    ],
  },
  {
    category: "histoire",
    subjects: [
      "préhistoire",
      "paléolithique",
      "néolithique",
      "âge du bronze",
      "âge du fer",
      "Mésopotamie",
      "Babylone",
      "Assyrie",
      "Sumer",
      "Égypte antique",
      "Grèce antique",
      "Rome antique",
      "Empire perse",
      "Empire chinois",
      "dynastie Tang",
      "dynastie Ming",
      "dynastie Qing",
      "Vikings",
      "Normands",
      "Charlemagne",
      "Empire carolingien",
      "Croisades",
      "Templiers",
      "Inquisition",
      "Reconquista",
      "Guerre de Cent Ans",
      "Guerre de Trente Ans",
      "Guerre de Sept Ans",
      "Révolution américaine",
      "Révolution haïtienne",
      "Révolution russe",
      "Guerre de Sécession",
      "Guerre d'Espagne",
      "Guerre du Vietnam",
      "Guerre de Corée",
      "Guerre d'Algérie",
      "Guerre d'Indochine",
      "Mur de Berlin",
      "chute du communisme",
      "perestroïka",
      "apartheid",
      "droits civiques",
      "Martin Luther King",
      "Nelson Mandela",
      "colonisation de l'Afrique",
      "traite négrière",
      "esclavage",
      "silk road",
      "route de la soie",
      "commerce maritime",
      "imprimerie",
      "révolution industrielle",
      "machine à vapeur",
      "découverte de la pénicilline",
      "vaccin",
      "Louis Pasteur",
      "Renaissance",
      "Siècle des Lumières",
      "Romantisme",
    ],
  },
  {
    category: "geographie",
    subjects: [
      "France",
      "Japon",
      "Corée du Sud",
      "États-Unis",
      "Chine",
      "Inde",
      "Brésil",
      "Russie",
      "Canada",
      "Australie",
      "Allemagne",
      "Italie",
      "Espagne",
      "Portugal",
      "Royaume-Uni",
      "Mexique",
      "Argentine",
      "Égypte",
      "Maroc",
      "Algérie",
      "Tunisie",
      "Sénégal",
      "Nigeria",
      "Afrique du Sud",
      "Kenya",
      "Éthiopie",
      "Thaïlande",
      "Vietnam",
      "Indonésie",
      "Philippines",
      "Turquie",
      "Iran",
      "Arabie Saoudite",
      "Israël",
      "Palestine",
      "Suisse",
      "Belgique",
      "Pays-Bas",
      "Suède",
      "Norvège",
      "Finlande",
      "Danemark",
      "Pologne",
      "Ukraine",
      "Grèce",
      "Paris",
      "Lyon",
      "Marseille",
      "Tokyo",
      "Séoul",
      "New York",
      "Londres",
      "Berlin",
      "Moscou",
      "Pékin",
      "Shanghai",
      "Bombay",
      "Le Caire",
      "Istanbul",
      "Dubaï",
      "Singapour",
      "Hong Kong",
      "océan Pacifique",
      "océan Atlantique",
      "océan Indien",
      "océan Arctique",
      "désert du Sahara",
      "désert de Gobi",
      "Amazonie",
      "forêt tropicale",
      "Himalaya",
      "Alpes",
      "Andes",
      "Rocheuses",
      "Caucase",
      "fleuve Amazone",
      "Nil",
      "Mississippi",
      "Yangtze",
      "Gange",
      "canal de Suez",
      "canal de Panama",
      "détroit de Gibraltar",
    ],
  },
  {
    category: "sport",
    subjects: [
      "football",
      "basketball",
      "tennis",
      "rugby",
      "cricket",
      "baseball",
      "handball",
      "volleyball",
      "hockey sur glace",
      "football américain",
      "golf",
      "athlétisme",
      "natation",
      "cyclisme",
      "boxe",
      "MMA",
      "UFC",
      "judo",
      "karaté",
      "taekwondo",
      "aïkido",
      "kung fu",
      "BJJ",
      "escrime",
      "tir à l'arc",
      "équitation",
      "aviron",
      "voile",
      "ski alpin",
      "ski de fond",
      "snowboard",
      "patinage",
      "hockey",
      "Formule 1",
      "rallye",
      "MotoGP",
      "NASCAR",
      "IndyCar",
      "Jeux Olympiques",
      "Jeux Olympiques d'été",
      "Jeux Olympiques d'hiver",
      "Coupe du Monde",
      "Euro",
      "Ligue des Champions",
      "NBA",
      "NFL",
      "NHL",
      "Tour de France",
      "Wimbledon",
      "Roland-Garros",
      "US Open",
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Kylian Mbappé",
      "Neymar",
      "LeBron James",
      "Michael Jordan",
      "Kobe Bryant",
      "Serena Williams",
      "Rafael Nadal",
      "Roger Federer",
      "Novak Djokovic",
    ],
  },
  {
    category: "musique",
    subjects: [
      "rock",
      "pop",
      "jazz",
      "blues",
      "classique",
      "électronique",
      "techno",
      "house",
      "dubstep",
      "trance",
      "drum and bass",
      "ambient",
      "hip-hop",
      "rap",
      "R&B",
      "soul",
      "funk",
      "reggae",
      "ska",
      "punk",
      "metal",
      "heavy metal",
      "death metal",
      "black metal",
      "power metal",
      "country",
      "folk",
      "bluegrass",
      "gospel",
      "flamenco",
      "K-pop",
      "J-pop",
      "anime music",
      "vocaloid",
      "lo-fi",
      "guitare",
      "piano",
      "batterie",
      "basse",
      "violon",
      "violoncelle",
      "saxophone",
      "trompette",
      "flûte",
      "accordéon",
      "harpe",
      "Beatles",
      "Rolling Stones",
      "Led Zeppelin",
      "Pink Floyd",
      "Queen",
      "Michael Jackson",
      "Madonna",
      "Prince",
      "David Bowie",
      "Eminem",
      "Tupac",
      "Notorious BIG",
      "Jay-Z",
      "Kanye West",
      "BTS",
      "Blackpink",
      "Stray Kids",
      "TWICE",
      "Daft Punk",
      "Deadmau5",
      "Tiësto",
      "Calvin Harris",
      "Mozart",
      "Beethoven",
      "Bach",
      "Chopin",
      "Debussy",
      "Stravinsky",
      "solfège",
      "accordage",
      "gamme musicale",
      "harmonie",
      "contrepoint",
    ],
  },
  {
    category: "cinema",
    subjects: [
      "cinéma",
      "histoire du cinéma",
      "âge d'or d'Hollywood",
      "Nouvelle Vague",
      "néoréalisme italien",
      "expressionnisme allemand",
      "cinéma japonais",
      "Studio Ghibli",
      "Hayao Miyazaki",
      "Akira Kurosawa",
      "Alfred Hitchcock",
      "Steven Spielberg",
      "Martin Scorsese",
      "Quentin Tarantino",
      "Christopher Nolan",
      "Stanley Kubrick",
      "Francis Ford Coppola",
      "Ridley Scott",
      "Denis Villeneuve",
      "Star Wars",
      "Seigneur des Anneaux",
      "Harry Potter",
      "Marvel Cinematic Universe",
      "DC Comics",
      "Batman",
      "Superman",
      "Spider-Man",
      "Iron Man",
      "Matrix",
      "Inception",
      "Interstellar",
      "Dune",
      "Blade Runner",
      "Pulp Fiction",
      "Goodfellas",
      "The Godfather",
      "Casablanca",
      "anime",
      "Studio Ghibli films",
      "Your Name",
      "Demon Slayer",
      "Attack on Titan",
      "One Piece",
      "Naruto",
      "Bleach",
      "Dragon Ball",
      "Hunter x Hunter",
      "Fullmetal Alchemist",
      "Death Note",
      "Cowboy Bebop",
      "Evangelion",
      "Oscars",
      "Cannes Film Festival",
      "Sundance Film Festival",
      "effets spéciaux",
      "CGI",
      "motion capture",
      "stuntman",
    ],
  },
  {
    category: "sante",
    subjects: [
      "système immunitaire",
      "vaccin",
      "anticorps",
      "virus",
      "bactérie",
      "grippe",
      "COVID-19",
      "rhume",
      "angine",
      "bronchite",
      "pneumonie",
      "diabète",
      "hypertension",
      "cholestérol",
      "maladie cardiovasculaire",
      "cancer",
      "chimiothérapie",
      "radiothérapie",
      "immunothérapie",
      "Alzheimer",
      "Parkinson",
      "sclérose en plaques",
      "épilepsie",
      "allergie",
      "asthme",
      "eczéma",
      "psoriasis",
      "arthrose",
      "arthrite",
      "osteoporose",
      "lombalgie",
      "migraine",
      "céphalée",
      "acouphène",
      "vertige",
      "nutrition",
      "obésité",
      "anorexie",
      "boulimie",
      "santé mentale",
      "dépression",
      "anxiété",
      "bipolarité",
      "schizophrénie",
      "TDAH",
      "autisme",
      "dyslexie",
      "dyspraxie",
      "premiers secours",
      "RCP",
      "massage cardiaque",
      "défibrillateur",
      "don de sang",
      "greffe d'organe",
      "moelle osseuse",
      "médecine alternative",
      "acupuncture",
      "homéopathie",
      "phytothérapie",
      "sommeil",
      "insomnie",
      "apnée",
      "narcolepsie",
      "grossesse",
      "accouchement",
      "allaitement",
      "IVG",
      "contraception",
      "pilule",
      "préservatif",
      "stérilet",
    ],
  },
  {
    category: "business",
    subjects: [
      "entrepreneuriat",
      "startup",
      "business plan",
      "levée de fonds",
      "capital risque",
      "business angel",
      "crowdfunding",
      "Kickstarter",
      "marketing",
      "marketing digital",
      "SEO",
      "SEA",
      "réseaux sociaux marketing",
      "influencer marketing",
      "content marketing",
      "email marketing",
      "e-commerce",
      "dropshipping",
      "Amazon FBA",
      "Shopify",
      "WooCommerce",
      "freelance",
      "auto-entrepreneur",
      "SASU",
      "SARL",
      "EURL",
      "comptabilité",
      "bilan",
      "compte de résultat",
      "cash flow",
      "fiscalité",
      "TVA",
      "IS",
      "IR",
      "IFI",
      "ressources humaines",
      "recrutement",
      "paie",
      "droit du travail",
      "management",
      "leadership",
      "Agile",
      "Scrum",
      "Kanban",
      "négociation",
      "vente",
      "prospection",
      "CRM",
      "Salesforce",
      "stratégie d'entreprise",
      "avantage concurrentiel",
      "Porter",
      "blue ocean strategy",
      "disruption",
      "innovation",
      "propriété intellectuelle",
      "brevet",
      "marque déposée",
      "copyright",
      "droit commercial",
      "contrat",
      "CGV",
      "RGPD",
    ],
  },
  {
    category: "animaux",
    subjects: [
      "chien",
      "chat",
      "cheval",
      "vache",
      "mouton",
      "chèvre",
      "cochon",
      "poule",
      "canard",
      "lapin",
      "hamster",
      "cobaye",
      "furet",
      "aquarium",
      "poisson rouge",
      "poisson tropical",
      "koi",
      "perroquet",
      "cockatiel",
      "perruche",
      "canari",
      "reptile",
      "tortue",
      "lézard",
      "gecko",
      "iguane",
      "serpent",
      "lion",
      "tigre",
      "léopard",
      "guépard",
      "jaguar",
      "panthère",
      "éléphant",
      "girafe",
      "rhinocéros",
      "hippopotame",
      "zèbre",
      "ours",
      "loup",
      "renard",
      "cerf",
      "sanglier",
      "dauphin",
      "baleine",
      "orque",
      "requin",
      "raie",
      "aigle",
      "faucon",
      "hibou",
      "chouette",
      "vautour",
      "abeille",
      "guêpe",
      "fourmi",
      "papillon",
      "mante religieuse",
      "araignée",
      "scorpion",
      "centipède",
      "corail",
      "méduse",
      "pieuvre",
      "calmar",
      "seiche",
      "extinction",
      "espèce protégée",
      "conservation",
      "WWF",
    ],
  },
  {
    category: "art_craft",
    subjects: [
      "dessin",
      "peinture",
      "aquarelle",
      "huile",
      "acrylique",
      "gouache",
      "pastel",
      "fusain",
      "croquis",
      "perspective",
      "anatomie artistique",
      "calligraphie",
      "typographie",
      "lettrage",
      "graffiti",
      "street art",
      "poterie",
      "céramique",
      "sculpture",
      "modelage",
      "terre cuite",
      "tricot",
      "crochet",
      "broderie",
      "couture",
      "tapisserie",
      "menuiserie",
      "ébénisterie",
      "sculpture sur bois",
      "marqueterie",
      "verrerie",
      "vitrail",
      "soufflage de verre",
      "bijouterie",
      "joaillerie",
      "orfèvrerie",
      "diamant",
      "or",
      "argent",
      "tatouage",
      "piercing",
      "body art",
      "photographie",
      "portrait",
      "paysage",
      "macro",
      "street photography",
      "Lightroom",
      "Photoshop",
      "GIMP",
      "Procreate",
      "design graphique",
      "logo",
      "branding",
      "UI design",
      "UX design",
      "Figma",
      "Adobe Illustrator",
      "InDesign",
    ],
  },
];

// ─── Tracker pour éviter de répéter les mêmes sujets ─────────────────────────
const learnedSubjects = new Set<string>();
let topicIndex = 0;
let subjectIndex = 0;

function getNextSubject(): { category: string; subject: string } | null {
  if (LEARN_TOPICS.length === 0) return null;

  let attempts = 0;
  while (attempts < 100) {
    const topic = LEARN_TOPICS[topicIndex];
    if (subjectIndex >= topic.subjects.length) {
      topicIndex = (topicIndex + 1) % LEARN_TOPICS.length;
      subjectIndex = 0;
      continue;
    }

    const subject = topic.subjects[subjectIndex];
    subjectIndex++;
    attempts++;

    const key = `${topic.category}:${subject}`;
    if (!learnedSubjects.has(key)) {
      learnedSubjects.add(key);
      return { category: topic.category, subject };
    }
  }

  // Tous les sujets ont été traités — reset
  logger.info("[SelfLearner] 🔄 Tous les sujets ont été traités — reset du cycle");
  learnedSubjects.clear();
  return null;
}

// ─── Récupérer un résumé Wikipédia (gratuit, pas d'API payante) ──────────────
async function fetchWikipediaSummary(subject: string, lang = "fr"): Promise<string | null> {
  try {
    // Search
    const searchUrl = `https://${lang}.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(subject)}&format=json&srlimit=1`;
    const searchRes = await fetch(searchUrl, { signal: AbortSignal.timeout(8000) });
    if (!searchRes.ok) return null;
    const searchData = (await searchRes.json()) as {
      query?: { search?: Array<{ title: string }> };
    };
    const title = searchData.query?.search?.[0]?.title;
    if (!title) return null;

    // Summary
    const summaryUrl = `https://${lang}.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`;
    const summaryRes = await fetch(summaryUrl, { signal: AbortSignal.timeout(8000) });
    if (!summaryRes.ok) return null;
    const summary = (await summaryRes.json()) as {
      title: string;
      extract: string;
      content_urls?: { desktop?: { page: string } };
    };

    if (!summary.extract || summary.extract.length < 20) return null;

    return `**${summary.title}**\n\n${summary.extract}\n\nSource: ${summary.content_urls?.desktop?.page || `https://${lang}.wikipedia.org/wiki/${encodeURIComponent(title)}`}`;
  } catch {
    return null;
  }
}

// ─── Récupérer une définition Wiktionnaire (gratuit) ─────────────────────────
async function fetchWiktionaryDefinition(word: string, lang = "fr"): Promise<string | null> {
  try {
    const restUrl = `https://${lang}.wiktionary.org/api/rest_v1/page/definition/${encodeURIComponent(word)}`;
    const res = await fetch(restUrl, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return null;
    const data = (await res.json()) as {
      definitions?: Array<{ partOfSpeech?: string; definition: string }>;
    };
    if (!data.definitions || data.definitions.length === 0) return null;

    const defs = data.definitions
      .slice(0, 3)
      .map((d) => `(${d.partOfSpeech || ""}) ${d.definition.replace(/<[^>]+>/g, "").trim()}`)
      .join("\n");

    return `**${word}**\n\n${defs}\n\nSource: https://${lang}.wiktionary.org/wiki/${encodeURIComponent(word)}`;
  } catch {
    return null;
  }
}

// ─── Générer une Q&A et la sauvegarder dans Obsidian ──────────────────────────
async function learnSubject(category: string, subject: string): Promise<boolean> {
  // Vérifier si on a déjà une Q&A pour ce sujet
  const existing = await searchQA(subject);
  if (existing) {
    logger.debug(`[SelfLearner] ⏭️ Déjà appris: ${subject} (catégorie: ${existing.category})`);
    return false;
  }

  // Construire la question
  const question = `Qu'est-ce que ${subject} ?`;

  // Essayer Wikipédia d'abord
  let answer = await fetchWikipediaSummary(subject);

  // Si pas de résultat Wikipédia, essayer le Wiktionnaire
  if (!answer) {
    answer = await fetchWiktionaryDefinition(subject);
  }

  // Si toujours rien, essayer en anglais
  if (!answer) {
    answer = await fetchWikipediaSummary(subject, "en");
  }

  if (!answer) {
    logger.debug(`[SelfLearner] ❌ Pas de source trouvée pour: ${subject}`);
    return false;
  }

  // Sauvegarder dans Obsidian
  await saveQA(question, answer, category);
  logger.info(`[SelfLearner] 📚 Appris: ${subject} (catégorie: ${category}) → Obsidian`);
  return true;
}

// ─── Cycle d'apprentissage ────────────────────────────────────────────────────
async function learnBatch(): Promise<void> {
  if (isLearning) return;
  isLearning = true;

  try {
    let learned = 0;
    for (let i = 0; i < BATCH_SIZE; i++) {
      const next = getNextSubject();
      if (!next) break;

      const success = await learnSubject(next.category, next.subject);
      if (success) learned++;

      // Petite pause entre chaque requête pour ne pas spammer Wikipédia
      await new Promise((resolve) => setTimeout(resolve, 2000));
    }

    if (learned > 0) {
      logger.info(`[SelfLearner] ✅ Batch terminé: ${learned} Q&A apprises`);
    }
  } catch (error) {
    logger.warn(
      `[SelfLearner] ⚠️ Erreur apprentissage: ${error instanceof Error ? error.message : String(error)}`,
    );
  } finally {
    isLearning = false;
  }
}

// ─── Démarrage / arrêt ────────────────────────────────────────────────────────
export function startSelfLearner(): void {
  if (learnTimer) return;

  // Premier batch après 30s (laisser le bot démarrer)
  setTimeout(() => {
    void learnBatch();
  }, 30_000);

  // Puis toutes les 10 minutes
  learnTimer = setInterval(() => {
    void learnBatch();
  }, LEARN_INTERVAL_MS);

  if (learnTimer.unref) learnTimer.unref();
  logger.info(
    `[SelfLearner] 🧠 Auto-apprentissage démarré (${BATCH_SIZE} Q&A toutes les ${LEARN_INTERVAL_MS / 60000}min)`,
  );
}

export function stopSelfLearner(): void {
  if (learnTimer) {
    clearInterval(learnTimer);
    learnTimer = null;
    logger.info("[SelfLearner] 🛑 Auto-apprentissage arrêté");
  }
}

export function getSelfLearnerStatus(): {
  active: boolean;
  subjectsLearned: number;
  nextBatchInMs: number | null;
} {
  return {
    active: learnTimer !== null,
    subjectsLearned: learnedSubjects.size,
    nextBatchInMs: learnTimer ? LEARN_INTERVAL_MS : null,
  };
}
