#!/usr/bin/env bash
# ============================================================================
#  Cloud Agent install script — Discord Surveillance Bot
#  Idempotent: safe to run multiple times. Prepares system packages, the
#  local Postgres/Redis, Node dependencies, and the Prisma schema so the
#  project is fully runnable (npm test / npm start).
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[install] Installing system packages (Postgres, Redis, build tools)..."
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends \
  postgresql postgresql-contrib redis-server \
  build-essential python3 pkg-config openssl \
  libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

echo "[install] Starting Postgres & Redis (needed for schema push)..."
sudo service redis-server start || true
sudo service postgresql start || true

echo "[install] Ensuring 'discord_bot' role and database exist..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL' || true
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'discord_bot') THEN
    CREATE ROLE discord_bot LOGIN PASSWORD 'discord_bot';
  END IF;
END
$$;
ALTER ROLE discord_bot CREATEDB;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='discord_bot'" | grep -q 1; then
  sudo -u postgres createdb -O discord_bot discord_bot
fi

echo "[install] Creating .env (only if missing; uses injected secrets when present)..."
if [ ! -f .env ]; then
  cat > .env <<EOF
# Auto-generated by .cursor/install.sh for local development.
# Replace DISCORD_* with real values (or add them as Cloud Agent secrets)
# to let the bot connect to the Discord gateway via 'npm start'.
DISCORD_TOKEN="${DISCORD_TOKEN:-dev-placeholder-token}"
DISCORD_CLIENT_ID="${DISCORD_CLIENT_ID:-000000000000000000}"
DISCORD_GUILD_ID="${DISCORD_GUILD_ID:-000000000000000000}"
OWNER_ID="${OWNER_ID:-000000000000000000}"
DATABASE_URL="${DATABASE_URL:-postgresql://discord_bot:discord_bot@localhost:5432/discord_bot?schema=public}"
REDIS_URL="${REDIS_URL:-redis://localhost:6379}"
CONTROL_TOKEN="${CONTROL_TOKEN:-dev-control-token}"
NODE_ENV="${NODE_ENV:-development}"
EOF
fi

echo "[install] Installing Node dependencies (--ignore-scripts, matches Dockerfile)..."
npm install --ignore-scripts

echo "[install] Patching native modules (raknet-native, discord-video-stream)..."
node -e "const fs=require('fs');const p='node_modules/raknet-native/binding.js';if(fs.existsSync(p)){let c=fs.readFileSync(p,'utf8');c=c.replace(\"require('bindings')\",\"function(){return new Proxy({},{get:function(){return function(){}}})}\");fs.writeFileSync(p,c);console.log('Patched raknet-native')}"
node scripts/patch-video-stream.cjs || true

echo "[install] Generating Prisma client and applying schema..."
npx prisma generate
npx prisma db push

echo "[install] Done."
