/**
 * Language Detector — Dictionaries for 17 languages
 * Lightweight offline detection using common word indicators + script checks.
 */

export type SupportedLang =
  | "fr"
  | "en"
  | "de"
  | "es"
  | "pt"
  | "it"
  | "ja"
  | "zh"
  | "ar"
  | "ru"
  | "nl"
  | "sv"
  | "no"
  | "cs"
  | "pl"
  | "tr"
  | "ko";

interface LangProfile {
  code: SupportedLang;
  name: string;
  nativeName: string;
  flag: string;
  indicators: string[];
  scriptRegex?: RegExp;
  threshold: number;
}

const LANG_PROFILES: LangProfile[] = [
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    threshold: 2,
    indicators: [
      " le ",
      " la ",
      " les ",
      " un ",
      " une ",
      " des ",
      " du ",
      " au ",
      " et ",
      " ou ",
      " mais ",
      " pour ",
      " avec ",
      " sans ",
      " sur ",
      " dans ",
      " par ",
      " être ",
      " avoir ",
      " faire ",
      " pas ",
      " plus ",
      " très ",
      " bien ",
      " c'est ",
      " il ",
      " elle ",
      " nous ",
      " vous ",
      " ils ",
      " que ",
      " qui ",
      " ne ",
      " ce ",
      " cette ",
      " mon ",
      " ton ",
      " son ",
    ],
  },
  {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇬🇧",
    threshold: 2,
    indicators: [
      " the ",
      " and ",
      " or ",
      " but ",
      " for ",
      " with ",
      " without ",
      " on ",
      " in ",
      " at ",
      " to ",
      " from ",
      " by ",
      " is ",
      " are ",
      " was ",
      " were ",
      " be ",
      " have ",
      " has ",
      " will ",
      " would ",
      " could ",
      " should ",
      " not ",
      " no ",
      " yes ",
      " i ",
      " you ",
      " he ",
      " she ",
      " it ",
      " we ",
      " they ",
      " my ",
      " your ",
      " what ",
      " which ",
      " who ",
      " where ",
      " when ",
      " how ",
    ],
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    threshold: 2,
    indicators: [
      " der ",
      " die ",
      " das ",
      " den ",
      " dem ",
      " ein ",
      " eine ",
      " und ",
      " oder ",
      " aber ",
      " mit ",
      " ohne ",
      " auf ",
      " ist ",
      " sind ",
      " war ",
      " sein ",
      " haben ",
      " hat ",
      " nicht ",
      " kein ",
      " sehr ",
      " auch ",
      " ich ",
      " du ",
      " er ",
      " sie ",
      " es ",
      " wir ",
      " ihr ",
      " mein ",
      " dein ",
      " was ",
      " wer ",
      " wo ",
      " wann ",
      " wie ",
      " sich ",
      " für ",
      " zu ",
      " vom ",
      " zum ",
    ],
  },
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    threshold: 2,
    indicators: [
      " el ",
      " la ",
      " los ",
      " las ",
      " un ",
      " una ",
      " y ",
      " o ",
      " pero ",
      " para ",
      " con ",
      " sin ",
      " sobre ",
      " en ",
      " por ",
      " es ",
      " son ",
      " era ",
      " ser ",
      " estar ",
      " no ",
      " muy ",
      " también ",
      " yo ",
      " tú ",
      " él ",
      " ella ",
      " nosotros ",
      " ellos ",
      " mi ",
      " tu ",
      " su ",
      " que ",
      " qué ",
      " quién ",
      " cómo ",
      " dónde ",
      " cuándo ",
      " se ",
      " le ",
      " lo ",
    ],
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇵🇹",
    threshold: 2,
    indicators: [
      " o ",
      " a ",
      " os ",
      " as ",
      " um ",
      " uma ",
      " e ",
      " ou ",
      " mas ",
      " para ",
      " com ",
      " sem ",
      " em ",
      " por ",
      " é ",
      " são ",
      " era ",
      " ser ",
      " estar ",
      " não ",
      " muito ",
      " também ",
      " eu ",
      " ele ",
      " ela ",
      " nós ",
      " eles ",
      " meu ",
      " teu ",
      " seu ",
      " que ",
      " quem ",
      " como ",
      " onde ",
      " quando ",
      " de ",
      " do ",
      " da ",
      " se ",
      " lhe ",
    ],
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    threshold: 2,
    indicators: [
      " il ",
      " la ",
      " lo ",
      " i ",
      " le ",
      " gli ",
      " un ",
      " una ",
      " e ",
      " o ",
      " ma ",
      " per ",
      " con ",
      " senza ",
      " su ",
      " in ",
      " da ",
      " di ",
      " è ",
      " sono ",
      " era ",
      " essere ",
      " avere ",
      " non ",
      " molto ",
      " anche ",
      " io ",
      " tu ",
      " lui ",
      " lei ",
      " noi ",
      " voi ",
      " loro ",
      " mio ",
      " tuo ",
      " suo ",
      " che ",
      " chi ",
      " come ",
      " dove ",
      " quando ",
      " si ",
      " ci ",
      " vi ",
    ],
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    threshold: 1,
    scriptRegex: /[\u3040-\u309f\u30a0-\u30ff]/,
    indicators: [
      "です",
      "ます",
      "だ",
      "の",
      "に",
      "は",
      "が",
      "を",
      "で",
      "と",
      "も",
      "から",
      "まで",
      "して",
      "する",
      "いる",
      "ある",
      "なる",
      "私",
      "僕",
      "君",
      "何",
      "誰",
      "どこ",
      "いつ",
      "ください",
      "ありがとう",
    ],
  },
  {
    code: "zh",
    name: "Chinese",
    nativeName: "中文",
    flag: "🇨🇳",
    threshold: 1,
    scriptRegex: /[\u4e00-\u9fff]/,
    indicators: [
      "的",
      "是",
      "在",
      "和",
      "我",
      "你",
      "他",
      "她",
      "这",
      "那",
      "什",
      "么",
      "不",
      "没",
      "有",
      "能",
      "会",
      "要",
      "了",
      "请",
      "谢",
      "好",
      "个",
      "们",
    ],
  },
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    flag: "🇸🇦",
    threshold: 1,
    scriptRegex: /[\u0600-\u06ff]/,
    indicators: [
      "في",
      "من",
      "إلى",
      "على",
      "عن",
      "مع",
      "هذا",
      "هذه",
      "هو",
      "هي",
      "هم",
      "نحن",
      "أنا",
      "أنت",
      "ما",
      "كيف",
      "أين",
      "متى",
      "لماذا",
      "لا",
      "نعم",
      "كان",
      "ال",
      "و",
      "أو",
      "لكن",
      "لأن",
    ],
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    threshold: 1,
    scriptRegex: /[\u0400-\u04ff]/,
    indicators: [
      " и ",
      " или ",
      " но ",
      " в ",
      " на ",
      " с ",
      " без ",
      " это ",
      " я ",
      " ты ",
      " он ",
      " она ",
      " мы ",
      " вы ",
      " они ",
      " что ",
      " кто ",
      " как ",
      " где ",
      " когда ",
      " не ",
      " нет ",
      " да ",
      " очень ",
      " был ",
      " быть ",
      " для ",
      " от ",
      " к ",
      " по ",
    ],
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    threshold: 2,
    indicators: [
      " de ",
      " het ",
      " een ",
      " en ",
      " of ",
      " maar ",
      " met ",
      " zonder ",
      " op ",
      " in ",
      " aan ",
      " bij ",
      " naar ",
      " van ",
      " uit ",
      " is ",
      " zijn ",
      " was ",
      " hebben ",
      " heeft ",
      " niet ",
      " geen ",
      " zeer ",
      " ook ",
      " ik ",
      " jij ",
      " hij ",
      " zij ",
      " wij ",
      " jullie ",
      " mijn ",
      " jouw ",
      " wat ",
      " wie ",
      " hoe ",
      " waar ",
      " wanneer ",
      " waarom ",
      " voor ",
      " te ",
    ],
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    flag: "🇸🇪",
    threshold: 2,
    indicators: [
      " och ",
      " eller ",
      " men ",
      " för ",
      " att ",
      " med ",
      " utan ",
      " på ",
      " i ",
      " av ",
      " till ",
      " från ",
      " är ",
      " var ",
      " har ",
      " hade ",
      " inte ",
      " ingen ",
      " mycket ",
      " också ",
      " jag ",
      " du ",
      " han ",
      " hon ",
      " det ",
      " vi ",
      " ni ",
      " de ",
      " min ",
      " din ",
      " vad ",
      " vem ",
      " hur ",
      " var ",
      " när ",
      " varför ",
      " en ",
      " ett ",
    ],
  },
  {
    code: "no",
    name: "Norwegian",
    nativeName: "Norsk",
    flag: "🇳🇴",
    threshold: 2,
    indicators: [
      " og ",
      " eller ",
      " men ",
      " for ",
      " at ",
      " med ",
      " uten ",
      " på ",
      " i ",
      " av ",
      " til ",
      " fra ",
      " er ",
      " var ",
      " har ",
      " hadde ",
      " ikke ",
      " ingen ",
      " mye ",
      " også ",
      " jeg ",
      " du ",
      " han ",
      " hun ",
      " det ",
      " vi ",
      " dere ",
      " de ",
      " min ",
      " din ",
      " hva ",
      " hvem ",
      " hvordan ",
      " hvor ",
      " når ",
      " hvorfor ",
      " en ",
      " et ",
    ],
  },
  {
    code: "cs",
    name: "Czech",
    nativeName: "Čeština",
    flag: "🇨🇿",
    threshold: 2,
    indicators: [
      " a ",
      " nebo ",
      " ale ",
      " protože ",
      " s ",
      " bez ",
      " na ",
      " v ",
      " o ",
      " do ",
      " od ",
      " k ",
      " pro ",
      " je ",
      " jsou ",
      " byl ",
      " být ",
      " mít ",
      " ne ",
      " ano ",
      " velmi ",
      " také ",
      " ještě ",
      " já ",
      " ty ",
      " on ",
      " ona ",
      " my ",
      " vy ",
      " oni ",
      " můj ",
      " tvůj ",
      " co ",
      " kdo ",
      " jak ",
      " kde ",
      " kdy ",
      " proč ",
    ],
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "Polski",
    flag: "🇵🇱",
    threshold: 2,
    indicators: [
      " i ",
      " lub ",
      " ale ",
      " ponieważ ",
      " z ",
      " bez ",
      " na ",
      " w ",
      " o ",
      " do ",
      " od ",
      " dla ",
      " jest ",
      " są ",
      " był ",
      " być ",
      " mieć ",
      " nie ",
      " tak ",
      " bardzo ",
      " też ",
      " jeszcze ",
      " ja ",
      " ty ",
      " on ",
      " ona ",
      " my ",
      " wy ",
      " oni ",
      " mój ",
      " twój ",
      " co ",
      " kto ",
      " jak ",
      " gdzie ",
      " kiedy ",
      " dlaczego ",
      " tego ",
      " tej ",
    ],
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    flag: "🇹🇷",
    threshold: 2,
    indicators: [
      " ve ",
      " veya ",
      " ama ",
      " çünkü ",
      " ile ",
      " olmadan ",
      " üzerinde ",
      " için ",
      " de ",
      " da ",
      " var ",
      " yok ",
      " değil ",
      " çok ",
      " daha ",
      " henüz ",
      " ben ",
      " sen ",
      " o ",
      " biz ",
      " siz ",
      " onlar ",
      " benim ",
      " senin ",
      " onun ",
      " bizim ",
      " ne ",
      " kim ",
      " nasıl ",
      " nerede ",
      " ne zaman ",
      " neden ",
      " bu ",
      " şu ",
      " bir ",
      " mı ",
      " mi ",
      " mu ",
      " mü ",
    ],
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    threshold: 1,
    scriptRegex: /[\uac00-\ud7af]/,
    indicators: [
      "입니다",
      "습니다",
      "다",
      "의",
      "에",
      "는",
      "가",
      "을",
      "를",
      "로",
      "과",
      "와",
      "에서",
      "으로",
      "하고",
      "있다",
      "없다",
      "나",
      "너",
      "그",
      "그녀",
      "우리",
      "너희",
      "그들",
      "무엇",
      "누가",
      "어디",
      "언제",
      "왜",
      "어떻게",
      "주세요",
      "감사",
    ],
  },
];

// ─── Detection Logic ─────────────────────────────────────────────────────

export interface DetectionResult {
  lang: SupportedLang;
  confidence: number;
  nativeName: string;
  flag: string;
}

/**
 * Detect the language of a text using offline dictionaries.
 * Returns the best match with confidence score (0-1).
 */
export function detectLanguage(text: string): DetectionResult {
  if (!text || text.trim().length === 0) {
    return { lang: "en", confidence: 0, nativeName: "English", flag: "🇬🇧" };
  }

  const lowerText = " " + text.toLowerCase().trim() + " ";
  const scores: { profile: LangProfile; hits: number }[] = [];

  for (const profile of LANG_PROFILES) {
    // Script-based detection (high confidence for non-Latin scripts)
    if (profile.scriptRegex) {
      const scriptMatches = text.match(profile.scriptRegex);
      if (scriptMatches && scriptMatches.length > 0) {
        scores.push({ profile, hits: Math.max(profile.threshold, scriptMatches.length) });
        continue;
      }
    }

    // Indicator-based detection
    let hits = 0;
    for (const indicator of profile.indicators) {
      if (lowerText.includes(indicator)) hits++;
    }
    if (hits >= profile.threshold) {
      scores.push({ profile, hits });
    }
  }

  if (scores.length === 0) {
    return { lang: "en", confidence: 0.1, nativeName: "English", flag: "🇬🇧" };
  }

  // Sort by hits descending
  scores.sort((a, b) => b.hits - a.hits);
  const best = scores[0];
  const totalHits = scores.reduce((sum, s) => sum + s.hits, 0);
  const confidence = Math.min(1, best.hits / Math.max(totalHits, 1));

  return {
    lang: best.profile.code,
    confidence,
    nativeName: best.profile.nativeName,
    flag: best.profile.flag,
  };
}

/**
 * Get the native name for a language code.
 */
export function getNativeName(code: SupportedLang): string {
  const p = LANG_PROFILES.find((p) => p.code === code);
  return p?.nativeName ?? code;
}

/**
 * Get the flag emoji for a language code.
 */
export function getFlag(code: SupportedLang): string {
  const p = LANG_PROFILES.find((p) => p.code === code);
  return p?.flag ?? "🌐";
}

/**
 * All supported languages with metadata.
 */
export const LANGUAGES = LANG_PROFILES.map((p) => ({
  code: p.code,
  name: p.name,
  nativeName: p.nativeName,
  flag: p.flag,
}));
