import os

# Build the file line by line to avoid escaping issues
lines = []
lines.append('/**')
lines.append(' * control-server.ts - Micro-serveur de controle pour l''application Desktop')
lines.append(' *')
lines.append(' * Expose une API REST + WebSocket pour piloter le bot a distance')
lines.append(' * depuis l''application Electron (desktop-app/).')
lines.append(' * Securite : token Bearer (CONTROL_TOKEN dans .env)')
lines.append(' */')
lines.append('')
lines.append('import http from "http";')
lines.append('import { WebSocketServer, WebSocket } from "ws";')
lines.append('import os from "os";')
lines.append('import logger from "./utils/logger";')
lines.append('import { config } from "./config";')
lines.append('import { dedupCache } from "./utils/deduplicationCache";')
lines.append('import {')
lines.append('  checkFreeGames,')
lines.append('  startFreeGamesMonitoring,')
lines.append('  stopFreeGamesMonitoring,')
lines.append('} from "./cron/freeGamesCron";')
lines.append('import {')
lines.append('  checkTwitterAccounts,')
lines.append('  startTwitterMonitoring,')
lines.append('  stopTwitterMonitoring,')
lines.append('} from "./cron/twitterCron";')
lines.append('import {')
lines.append('  checkDeals,')
lines.append('  startDealsMonitoring,')
lines.append('  stopDealsMonitoring,')
lines.append('} from "./cron/dealsCron";')
lines.append('import {')
lines.append('  checkTrackedGames,')
lines.append('  startSteamNewsMonitoring,')
lines.append('  stopSteamNewsMonitoring,')
lines.append('} from "./cron/steamNewsCron";')
lines.append('import {')
lines.append('  checkPatchNotes,')
lines.append('  startGlobalPatchNotesMonitoring,')
lines.append('  stopGlobalPatchNotesMonitoring,')
lines.append('} from "./cron/globalPatchNotesCron";')
lines.append('import {')
lines.append('  checkInstantGamingNews,')
lines.append('  startInstantGamingNewsCheck,')
lines.append('  stopInstantGamingNewsCheck,')
lines.append('} from "./services/instantgaming-news";')
lines.append('import {')
lines.append('  checkInstantGamingGiveaway,')
lines.append('  startInstantGamingCheck,')
lines.append('  stopInstantGamingCheck,')
lines.append('} from "./services/instantgaming";')
lines.append('')

# Types
lines.append('// ─── Types ────────────────────────────────────────────────────────────────')
lines.append('')
lines.append('type PlatformId =')
lines.append('  | "free-games"')
lines.append('  | "twitter"')
lines.append('  | "deals"')
lines.append('  | "steam-news"')
lines.append('  | "patch-notes"')
lines.append('  | "instantgaming-news"')
lines.append('  | "instantgaming-giveaway";')
lines.append('')
lines.append('interface PlatformStatus {')
lines.append('  id: PlatformId;')
lines.append('  label: string;')
lines.append('  active: boolean;')
lines.append('  cacheCount: number;')
lines.append('}')
lines.append('')
lines.append('// ─── État global ─────────────────────────────────────────────────────────')
lines.append('')
lines.append('let server: http.Server | null = null;')
lines.append('let wss: WebSocketServer | null = null;')
lines.append('const wsClients = new Set<WebSocket>();')
lines.append('let clientRef: import("discord.js").Client | null = null;')
lines.append('const startTime = Date.now();')
lines.append('')
lines.append('/**')
lines.append(' * Plateforme activee par defaut au demarrage. On initialise a true,')
lines.append(' * les start*() seront appeles par startup.ts et appelleront activatePlatform().')
lines.append(' * Les stop*() appelleront deactivatePlatform().')
lines.append(' */')
lines.append('const platformActive: Record<PlatformId, boolean> = {')
lines.append('  "free-games": false,')
lines.append('  "twitter": false,')
lines.append('  "deals": false,')
lines.append('  "steam-news": false,')
lines.append('  "patch-notes": false,')
lines.append('  "instantgaming-news": false,')
lines.append('  "instantgaming-giveaway": false,')
lines.append('};')
lines.append('')
lines.append('const PLATFORM_LABELS: Record<PlatformId, string> = {')
lines.append('  "free-games": "Jeux gratuits (Epic/Steam/GOG...)",')
lines.append('  "twitter": "Twitter / X",')
lines.append('  "deals": "Bons plans (Dealabs/PPDG...)",')
lines.append('  "steam-news": "Actualites Steam",')
lines.append('  "patch-notes": "Patch notes globaux",')
lines.append('  "instantgaming-news": "Instant Gaming - News",')
lines.append('  "instantgaming-giveaway": "Instant Gaming - Giveaway",')
lines.append('};')
lines.append('')

# ─── Platform state management
lines.append('// ─── Gestion de l''etat des plateformes ───────────────────────────────────')
lines.append('')
lines.append('export function activatePlatform(id: PlatformId): void {')
lines.append('  platformActive[id] = true;')
lines.append('  broadcast({ type: "platform-update", platforms: getPlatformStatuses() });')
lines.append('}')
lines.append('')
lines.append('export function deactivatePlatform(id: PlatformId): void {')
lines.append('  platformActive[id] = false;')
lines.append('  broadcast({ type: "platform-update", platforms: getPlatformStatuses() });')
lines.append('}')
lines.append('')
lines.append('function getPlatformStatuses(): PlatformStatus[] {')
lines.append('  const stats = dedupCache.getStats();')
lines.append('  return (Object.keys(PLATFORM_LABELS) as PlatformId[]).map((id) => ({')
lines.append('    id,')
lines.append('    label: PLATFORM_LABELS[id],')
lines.append('    active: platformActive[id],')
lines.append('    cacheCount: stats[id] ?? 0,')
lines.append('  }));')
lines.append('}')
lines.append('')

# ─── Broadcast helper
lines.append('// ─── WebSocket Broadcast ──────────────────────────────────────────────────')
lines.append('')
lines.append('function broadcast(data: Record<string, unknown>): void {')
lines.append('  const payload = JSON.stringify(data);')
lines.append('  for (const client of wsClients) {')
lines.append('    if (client.readyState === WebSocket.OPEN) {')
lines.append('      client.send(payload);')
lines.append('    }')
lines.append('  }')
lines.append('}')
lines.append('')

# ─── Auth middleware
lines.append('// ─── Middleware d''authentification ───────────────────────────────────────')
lines.append('')
lines.append('function authCheck(req: http.IncomingMessage, res: http.ServerResponse): boolean {')
lines.append('  if (!config.controlToken) {')
lines.append('    res.writeHead(500, { "Content-Type": "application/json" });')
lines.append('    res.end(JSON.stringify({ error: "CONTROL_TOKEN non configure dans .env" }));')
lines.append('    return false;')
lines.append('  }')
lines.append('  const auth = req.headers.authorization || "";')
lines.append('  if (!auth.startsWith("Bearer ") || auth.slice(7) !== config.controlToken) {')
lines.append('    res.writeHead(401, { "Content-Type": "application/json" });')
lines.append('    res.end(JSON.stringify({ error: "Non autorise" }));')
lines.append('    return false;')
lines.append('  }')
lines.append('  return true;')
lines.append('}')
lines.append('')

# ─── GET /api/status
lines.append('// ─── Routes API ───────────────────────────────────────────────────────────')
lines.append('')
lines.append('function handleStatus(_req: http.IncomingMessage, res: http.ServerResponse): void {')
lines.append('  const mem = process.memoryUsage();')
lines.append('  const cpus = os.cpus();')
lines.append('  const loadAvg = os.loadavg().map((v) => Math.round(v * 100) / 100);')
lines.append('')
lines.append('  // CPU usage calculation')
lines.append('  let totalIdle = 0;')
lines.append('  let totalTick = 0;')
lines.append('  for (const cpu of cpus) {')
lines.append('    for (const type of Object.keys(cpu.times) as (keyof typeof cpu.times)[]) {')
lines.append('      totalTick += cpu.times[type];')
lines.append('    }')
lines.append('    totalIdle += cpu.times.idle;')
lines.append('  }')
lines.append('  const cpuUsage = Math.round(((1 - totalIdle / totalTick) * 100) * 100) / 100;')
lines.append('')
lines.append('  const uptime = Math.floor((Date.now() - startTime) / 1000);')
lines.append('  const activePlatforms = Object.values(platformActive).filter(Boolean).length;')
lines.append('')
lines.append('  res.writeHe
